# AU Health Analytics - EDA
This notebook imports the master tables from the three AIHW Excel files as defined in `Tables.txt`.

In [4]:
import pandas as pd
import os

# File paths
ed_file = 'Emergency-department-care-2024-25.xlsx'
elective_file = 'Elective-surgery-waiting-times-2024-25.xlsx'
expenditure_file = 'hwe-105-health-expenditure-australia-2023-24-supplementary-tables.xlsx'

# Tables to import (from Tables.txt)
ed_tables = ['Table 2.2', 'Table 3.1', 'Table 4.5', 'Table 4.9', 'Table 5.1', 'Table 5.3', 'Table 6.1', 'Table 6.3']
elective_tables = ['Table 2.1', 'Table 2.4', 'Table 3.1', 'Table 3.2', 'Table 4.1', 'Table 4.2', 'Table 4.4', 'Table 4.10']
expenditure_tables = ['Table 3', 'Table 4', 'Table 5', 'Table 28', 'Table 29', 'Table 30', 'Table A3', 'Table B3', 'Table B6', 'Table B9', 'Table B12', 'Table B15', 'Table B18', 'Table B21', 'Table B24']

In [9]:
def load_tables(file_path, tables):
    data = {}
    print(f"Loading tables from {file_path}...")
    for table in tables:
             # header=1 skips the title row and uses the second row as columns
        df = pd.read_excel(file_path, sheet_name=table, header=1)
    
             # Remove rows that are entirely empty (common in Excel footers)
        df = df.dropna(how='all').reset_index(drop=True)
   
        data[table] = df
        print(f"  Loaded {table}")
    return data
   
   #Load data into dictionaries
ed_data = load_tables(ed_file, ed_tables)
elective_data = load_tables(elective_file, elective_tables)
expenditure_data = load_tables(expenditure_file, expenditure_tables)

Loading tables from Emergency-department-care-2024-25.xlsx...
  Loaded Table 2.2
  Loaded Table 3.1
  Loaded Table 4.5
  Loaded Table 4.9
  Loaded Table 5.1
  Loaded Table 5.3
  Loaded Table 6.1
  Loaded Table 6.3
Loading tables from Elective-surgery-waiting-times-2024-25.xlsx...
  Loaded Table 2.1
  Loaded Table 2.4
  Loaded Table 3.1
  Loaded Table 3.2
  Loaded Table 4.1
  Loaded Table 4.2
  Loaded Table 4.4
  Loaded Table 4.10
Loading tables from hwe-105-health-expenditure-australia-2023-24-supplementary-tables.xlsx...
  Loaded Table 3
  Loaded Table 4
  Loaded Table 5
  Loaded Table 28
  Loaded Table 29
  Loaded Table 30
  Loaded Table A3
  Loaded Table B3
  Loaded Table B6
  Loaded Table B9
  Loaded Table B12
  Loaded Table B15
  Loaded Table B18
  Loaded Table B21
  Loaded Table B24

In [10]:
# Example: Check the first few rows of ED Table 2.2
ed_data['Table 2.2'].head(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25,Average annual change (%) last five years,Change (%) since last year
0,NSW,Presentations,3.068572e+06,3.012992e+06,3.076083e+06,3.178428e+06,3.160473e+06,0.7,-0.56
1,Vic,Presentations,1.772359e+06,1.856312e+06,1.894732e+06,1.923674e+06,1.978267e+06,2.8,2.84
2,Qld,Presentations,1.887381e+06,1.867860e+06,1.735935e+06,1.770087e+06,1.766839e+06,-1.6,-0.18
3,WA,Presentations,9.978160e+05,9.915220e+05,9.941120e+05,1.022259e+06,1.027017e+06,0.7,0.47
4,SA,Presentations,5.805750e+05,5.728860e+05,5.986660e+05,6.057250e+05,6.228760e+05,1.8,2.83
5,Tas,Presentations,1.702870e+05,1.732760e+05,1.738880e+05,1.776390e+05,1.831200e+05,1.8,3.09
6,ACT,Presentations,1.537130e+05,1.436930e+05,1.457180e+05,1.560290e+05,1.676030e+05,2.2,7.42
7,NT,Presentations,1.776540e+05,1.713360e+05,1.817850e+05,1.845600e+05,1.881170e+05,1.4,1.93
8,Total,Presentations,8.808357e+06,8.789877e+06,8.800919e+06,9.018401e+06,9.094312e+06,0.8,0.84
9,NSW,"Age-standardised rate per 1,000 population",3.716443e+02,3.656196e+02,3.676223e+02,3.709436e+02,3.615045e+02,-0.7,-2.54

In [11]:
for name, df in ed_data.items():
    print("\n====================")
    print(name)
    print("====================")
    print("Shape:", df.shape)
    print("Columns:", df.columns.tolist())
    print(df.head(3))

====================
Table 2.2
====================
Shape: (22, 9)
Columns: ['State/territory', 'Measure', '2020–21', '2021–22', '2022–23', '2023–24', '2024–25', 'Average annual change (%) last five years', 'Change (%) since last year']
  State/territory        Measure    2020–21    2021–22    2022–23    2023–24  \
0             NSW  Presentations  3068572.0  3012992.0  3076083.0  3178428.0
1             Vic  Presentations  1772359.0  1856312.0  1894732.0  1923674.0
2             Qld  Presentations  1887381.0  1867860.0  1735935.0  1770087.0

     2024–25  Average annual change (%) last five years  \
0  3160473.0                                        0.7
1  1978267.0                                        2.8
2  1766839.0                                       -1.6

   Change (%) since last year
0                       -0.56
1                        2.84
2                       -0.18

====================
Table 3.1
====================
Shape: (34, 11)
Columns: ['Sex', 'Age group', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas(a)', 'ACT', 'NT', 'Total']
     Sex Age group       NSW       Vic      Qld       WA       SA  Tas(a)  \
0  Males       0–4  171812.0  109668.0  97787.0  59532.0  34951.0  7716.0
1  Males      5–14  164802.0   99439.0  87764.0  59263.0  31117.0  7955.0
2  Males     15–24  172904.0   98275.0  99673.0  54545.0  30243.0  9877.0

      ACT      NT     Total
0  9345.0  9260.0  500071.0
1  8813.0  8001.0  467154.0
2  9355.0  9652.0  484524.0

====================
Table 4.5
====================
Shape: (30, 10)
Columns: ['Principal diagnosis', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total']
                                 Principal diagnosis       NSW      Vic  \
0  A00–B99 \tCertain infectious and parasitic dis...  125772.0  88147.0
1                                C00–D48 \tNeoplasms    9216.0   5641.0
2  D50–D89 \tDiseases of the blood and blood-form...   14781.0  10647.0

       Qld       WA       SA     Tas     ACT      NT     Total
0  81851.0  54124.0  27069.0  7163.0  8178.0  8202.0  400506.0
1   6861.0   3234.0   1834.0   762.0   324.0   311.0   28183.0
2   8506.0   5166.0   3350.0   900.0   778.0   537.0   44665.0

====================
Table 4.9
====================
Shape: (28, 10)
Columns: ['Principal diagnosis', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total']
                                 Principal diagnosis       NSW       Vic  \
0                    R10 \tAbdominal and pelvic pain  155163.0  110782.0
1                     R07 \tPain in throat and chest  142661.0  108508.0
2  R69 \tUnknown and unspecified causes of morbidity  182306.0   50310.0

       Qld       WA       SA      Tas      ACT      NT     Total
0  83426.0  37360.0  27294.0   8412.0  10123.0  6518.0  439078.0
1  85241.0  40933.0  25766.0  10107.0   9184.0  7794.0  430194.0
2   7403.0   1410.0  49778.0   8431.0   1176.0   396.0  301210.0

====================
Table 5.1
====================
Shape: (34, 7)
Columns: ['State/territory', 'Measure', '2020–21', '2021–22', '2022–23', '2023–24', '2024–25']
  State/territory                                 Measure  2020–21  2021–22  \
0             NSW           Median waiting time (minutes)  14.0000  14.0000
1             NSW  90th percentile waiting time (minutes)  81.0000  89.0000
2             NSW             Proportion seen on time (%)  79.1574  77.0933

   2022–23  2023–24   2024–25
0   15.000  15.0000   15.0000
1  100.000  98.0000  104.0000
2   74.023  74.3605   73.2518

====================
Table 5.3
====================
Shape: (42, 11)
Columns: ['Peer group', 'Triage category', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total']
                                          Peer group Triage category      NSW  \
0  Principal referral and womens and children's h...   Resuscitation  99.9548
1  Principal referral and womens and children's h...       Emergency  74.9598
2  Principal referral and womens and children's h...          Urgent  67.9040

        Vic      Qld       WA       SA      Tas      ACT       NT    Total
0  100.0000  99.9595      100  98.5025   99.537   99.115      100  99.7970
1   64.2770  74.9079  63.2382  49.6451  39.0862  62.7306   36.512  66.9975
2   72.3761  67.5799  21.7646  35.8249  27.6252  47.9112  18.0986  59.0583

====================
Table 6.1
====================
Shape: (35, 7)
Columns: ['Admission status', 'State/territory', '2020–21', '2021–22', '2022–23', '2023–24', '2024–25']
                   Admission status State/territory 2020–21 2021–22 2022–23  \
0  Patient subsequently admitted(c)             NSW   15:25   17:55   20:53
1  Patient subsequently admitted(c)             Vic   12:46   16:10   18:55
2  Patient subsequently admitted(c)             Qld   10:21   12:22   14:44

  2023–24 2024–25
0   20:30   20:40
1   17:43   17:47
2   16:11   18:03

====================
Table 6.3
====================
Shape: (24, 7)
Columns: ['Admission status(b)', 'State/territory', '2020–21', '2021–22', '2022–23', '2023–24', '2024–25']
                          Admission status(b) State/territory  2020–21  \
0  All presentations to emergency departments             NSW  68.9650
1  All presentations to emergency departments             Vic  61.9723
2  All presentations to emergency departments             Qld  69.1127

   2021–22  2022–23  2023–24  2024–25
0  64.2372  58.6348  57.4209  56.3124
1  55.3146  51.9815  53.2019  52.6708
2  61.3550  53.9983  51.8571  49.9313

In [12]:
t22 = ed_data["Table 2.2"].copy()

# keep only the year columns
t22 = t22.drop(columns=[
    "Average annual change (%) last five years",
    "Change (%) since last year"
])

t22.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
0,NSW,Presentations,3068572.0,3012992.0,3076083.0,3178428.0,3160473.0
1,Vic,Presentations,1772359.0,1856312.0,1894732.0,1923674.0,1978267.0
2,Qld,Presentations,1887381.0,1867860.0,1735935.0,1770087.0,1766839.0
3,WA,Presentations,997816.0,991522.0,994112.0,1022259.0,1027017.0
4,SA,Presentations,580575.0,572886.0,598666.0,605725.0,622876.0

In [13]:
t22_long = t22.melt(
    id_vars=["State/territory", "Measure"],
    var_name="Year",
    value_name="Value"
)

t22_long.head()

  State/territory        Measure     Year      Value
0             NSW  Presentations  2020–21  3068572.0
1             Vic  Presentations  2020–21  1772359.0
2             Qld  Presentations  2020–21  1887381.0
3              WA  Presentations  2020–21   997816.0
4              SA  Presentations  2020–21   580575.0

In [15]:
valid_states = ["NSW","Vic","Qld","WA","SA","Tas","ACT","NT"]

t22_long = t22_long[t22_long["State/territory"].isin(valid_states)]

t22_long["State/territory"].unique()

<StringArray>
['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT']
Length: 8, dtype: str

In [16]:
t22_long["State/territory"].unique()

<StringArray>
['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT']
Length: 8, dtype: str

In [17]:
t22_long["Measure"].unique()

<StringArray>
['Presentations', 'Age-standardised rate per 1,000 population']
Length: 2, dtype: str

In [18]:
t22_long = t22_long.rename(columns={
    "State/territory": "state",
    "Measure": "measure",
    "Year": "year",
    "Value": "value"
})

t22_long.head()

  state        measure     year      value
0   NSW  Presentations  2020–21  3068572.0
1   Vic  Presentations  2020–21  1772359.0
2   Qld  Presentations  2020–21  1887381.0
3    WA  Presentations  2020–21   997816.0
4    SA  Presentations  2020–21   580575.0

In [19]:
len(t22_long)

80

In [20]:
t22_long.to_csv("ed_table_2_2_clean.csv", index=False)

In [21]:
t31 = ed_data["Table 3.1"]

print(t31["Sex"].unique())
print(t31["Age group"].unique())

<StringArray>
[                                                                                                                'Males',
                                                                                                               'Females',
                                                                                                               'Persons',
                                          '(a)     For Tasmania, the gender data item has been reported instead of sex.',
                                   '(b)     Includes presentations for which age group of the patient was not reported.',
                                     '(c)     Includes presentations for which the sex of the patient was not reported.',
 'Note: Appendix information with notes on definitions and data limitations is available to download at the link below:',
                                                      'https://www.aihw.gov.au/hospitals/other-resources/about-the-data',
                                                                                              'Technical specifications',
                                                                                                      'Back to contents']
Length: 10, dtype: str
<StringArray>
[     '0–4',     '5–14',    '15–24',    '25–34',    '35–44',    '45–54',
    '55–64',    '65–74',    '75–84',    '85–89',    '90–94',      '95+',
 'Total(b)', 'Total(c)',        nan]
Length: 15, dtype: str

In [22]:
t31 = ed_data["Table 3.1"].copy()

valid_sex = ["Males", "Females", "Persons"]

t31 = t31[t31["Sex"].isin(valid_sex)]

t31["Sex"].unique()

<StringArray>
['Males', 'Females', 'Persons']
Length: 3, dtype: str

In [23]:
t31 = t31[
    (~t31["Age group"].str.contains("Total", na=False)) &
    (t31["Age group"].notna())
]

t31["Age group"].unique()

<StringArray>
[  '0–4',  '5–14', '15–24', '25–34', '35–44', '45–54', '55–64', '65–74',
 '75–84', '85–89', '90–94',   '95+']
Length: 12, dtype: str

In [24]:
t31 = t31.rename(columns={
    "Tas(a)": "Tas"
})

t31.columns

Index(['Sex', 'Age group', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT',
       'Total'],
      dtype='str')

In [25]:
t31 = t31.drop(columns=["Total"])

t31.columns

Index(['Sex', 'Age group', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT',
       'NT'],
      dtype='str')

In [26]:
t31_long = t31.melt(
    id_vars=["Sex", "Age group"],
    var_name="state",
    value_name="value"
)

t31_long.head()

     Sex Age group state     value
0  Males       0–4   NSW  171812.0
1  Males      5–14   NSW  164802.0
2  Males     15–24   NSW  172904.0
3  Males     25–34   NSW  177347.0
4  Males     35–44   NSW  166763.0

In [27]:
t31_long = t31_long.rename(columns={
    "Sex": "sex",
    "Age group": "age_group"
})

t31_long.head()

     sex age_group state     value
0  Males       0–4   NSW  171812.0
1  Males      5–14   NSW  164802.0
2  Males     15–24   NSW  172904.0
3  Males     25–34   NSW  177347.0
4  Males     35–44   NSW  166763.0

In [28]:
len(t31_long)

192

In [29]:
t31_long["sex"].unique()

<StringArray>
['Males', 'Females']
Length: 2, dtype: str

In [30]:
t31

,Sex,Age group,NSW,Vic,Qld,WA,SA,Tas,ACT,NT
0,Males,0–4,171812.0,109668.0,97787.0,59532.0,34951.0,7716.0,9345.0,9260.0
1,Males,5–14,164802.0,99439.0,87764.0,59263.0,31117.0,7955.0,8813.0,8001.0
2,Males,15–24,172904.0,98275.0,99673.0,54545.0,30243.0,9877.0,9355.0,9652.0
3,Males,25–34,177347.0,111657.0,100864.0,60249.0,32428.0,10262.0,9409.0,12547.0
4,Males,35–44,166763.0,109923.0,98075.0,59852.0,32285.0,9435.0,9683.0,13075.0
5,Males,45–54,159327.0,100886.0,93622.0,52185.0,30353.0,8960.0,8528.0,12410.0
6,Males,55–64,164543.0,100489.0,90089.0,50121.0,32161.0,10077.0,7086.0,11782.0
7,Males,65–74,163999.0,94719.0,84622.0,46059.0,31353.0,10200.0,7079.0,7236.0
8,Males,75–84,156959.0,88329.0,79026.0,41249.0,29849.0,9607.0,6716.0,4192.0
9,Males,85–89,51758.0,28916.0,23556.0,13097.0,10314.0,2856.0,2160.0,715.0
10,Males,90–94,24227.0,13566.0,11067.0,6046.0,5391.0,1216.0,991.0,225.0
11,Males,95+,6995.0,3819.0,3040.0,1614.0,1712.0,236.0,267.0,52.0
13,Females,0–4,135693.0,84380.0,77293.0,47198.0,27166.0,6321.0,7575.0,7371.0
14,Females,5–14,129007.0,78929.0,73375.0,49113.0,26246.0,6824.0,7197.0,7242.0
15,Females,15–24,197927.0,121112.0,127897.0,69197.0,40629.0,13216.0,12056.0,12610.0
16,Females,25–34,218454.0,168831.0,133629.0,81078.0,46133.0,13780.0,14681.0,17684.0
17,Females,35–44,176486.0,132491.0,105982.0,68082.0,35406.0,10906.0,11939.0,17640.0
18,Females,45–54,153238.0,98931.0,92184.0,52610.0,30085.0,9539.0,8491.0,15189.0
19,Females,55–64,150775.0,94288.0,82476.0,47014.0,30500.0,9536.0,7228.0,10236.0
20,Females,65–74,153646.0,90468.0,77875.0,43025.0,30274.0,9481.0,6967.0,6245.0
21,Females,75–84,157027.0,90180.0,77693.0,40117.0,31387.0,9588.0,7265.0,3480.0
22,Females,85–89,60018.0,33920.0,27624.0,14600.0,12599.0,3255.0,2589.0,855.0
23,Females,90–94,33330.0,18118.0,15054.0,8145.0,7257.0,1681.0,1431.0,257.0
24,Females,95+,12653.0,6251.0,5629.0,2816.0,2906.0,515.0,510.0,75.0

In [31]:
t45 = ed_data["Table 4.5"]

print(t45["Principal diagnosis"].head(10))

0    A00–B99 \tCertain infectious and parasitic dis...
1                                  C00–D48 \tNeoplasms
2    D50–D89 \tDiseases of the blood and blood-form...
3    E00–E90 \tEndocrine, nutritional and metabolic...
4           F00–F99 \tMental and behavioural disorders
5             G00–G99 \tDiseases of the nervous system
6             H00–H59 \tDiseases of the eye and adnexa
7    H60–H95 \tDiseases of the ear and mastoid process
8         I00–I99 \tDiseases of the circulatory system
9         J00–J99 \tDiseases of the respiratory system
Name: Principal diagnosis, dtype: str

In [32]:
t45["Principal diagnosis"] = (
    t45["Principal diagnosis"]
    .str.replace("\t", " ", regex=False)
    .str.strip()
)

t45["Principal diagnosis"].head(10)

0    A00–B99  Certain infectious and parasitic dise...
1                                   C00–D48  Neoplasms
2    D50–D89  Diseases of the blood and blood-formi...
3    E00–E90  Endocrine, nutritional and metabolic ...
4            F00–F99  Mental and behavioural disorders
5              G00–G99  Diseases of the nervous system
6              H00–H59  Diseases of the eye and adnexa
7     H60–H95  Diseases of the ear and mastoid process
8          I00–I99  Diseases of the circulatory system
9          J00–J99  Diseases of the respiratory system
Name: Principal diagnosis, dtype: str

In [33]:
t45.tail(10)

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
20,U50–Y98 External causes of morbidity and mort...,0.0,0.0,867.0,1469.0,0.0,0.0,8.0,0.0,2344.0
21,Z00–Z99 Factors influencing health status and...,78749.0,25919.0,29554.0,37486.0,10535.0,14475.0,1527.0,11609.0,209854.0
22,Not stated/invalid,39203.0,93590.0,110844.0,74724.0,13.0,72.0,3989.0,16763.0,339198.0
23,Total,3160473.0,1978267.0,1766839.0,1027017.0,622876.0,183120.0,167603.0,188117.0,9094312.0
24,"U0.71 - Emergency use of U07.1 [COVID-19], vir...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,(a) Presentations include all types of visit.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
t45 = t45[t45["NSW"].notna()]

t45.tail()

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
19,"U07.1, U07.2, and U07.7 Emergency use of code...",14491.0,6794.0,6384.0,3983.0,124.0,691.0,790.0,722.0,33979.0
20,U50–Y98 External causes of morbidity and mort...,0.0,0.0,867.0,1469.0,0.0,0.0,8.0,0.0,2344.0
21,Z00–Z99 Factors influencing health status and...,78749.0,25919.0,29554.0,37486.0,10535.0,14475.0,1527.0,11609.0,209854.0
22,Not stated/invalid,39203.0,93590.0,110844.0,74724.0,13.0,72.0,3989.0,16763.0,339198.0
23,Total,3160473.0,1978267.0,1766839.0,1027017.0,622876.0,183120.0,167603.0,188117.0,9094312.0

In [35]:
t45 = t45[t45["Principal diagnosis"] != "Total"]

t45.tail()

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
18,"S00–T98 Injury, poisoning and certain other c...",675841.0,421189.0,374610.0,258590.0,138398.0,42665.0,38394.0,34459.0,1984146.0
19,"U07.1, U07.2, and U07.7 Emergency use of code...",14491.0,6794.0,6384.0,3983.0,124.0,691.0,790.0,722.0,33979.0
20,U50–Y98 External causes of morbidity and mort...,0.0,0.0,867.0,1469.0,0.0,0.0,8.0,0.0,2344.0
21,Z00–Z99 Factors influencing health status and...,78749.0,25919.0,29554.0,37486.0,10535.0,14475.0,1527.0,11609.0,209854.0
22,Not stated/invalid,39203.0,93590.0,110844.0,74724.0,13.0,72.0,3989.0,16763.0,339198.0

In [36]:
t45_long = t45.melt(
    id_vars=["Principal diagnosis"],
    var_name="state",
    value_name="value"
)

t45_long.head()

                                 Principal diagnosis state     value
0  A00–B99  Certain infectious and parasitic dise...   NSW  125772.0
1                                 C00–D48  Neoplasms   NSW    9216.0
2  D50–D89  Diseases of the blood and blood-formi...   NSW   14781.0
3  E00–E90  Endocrine, nutritional and metabolic ...   NSW   30455.0
4          F00–F99  Mental and behavioural disorders   NSW   94534.0

In [37]:
t45_long = t45_long.rename(columns={
    "Principal diagnosis": "principal_diagnosis"
})

t45_long.head()

                                 principal_diagnosis state     value
0  A00–B99  Certain infectious and parasitic dise...   NSW  125772.0
1                                 C00–D48  Neoplasms   NSW    9216.0
2  D50–D89  Diseases of the blood and blood-formi...   NSW   14781.0
3  E00–E90  Endocrine, nutritional and metabolic ...   NSW   30455.0
4          F00–F99  Mental and behavioural disorders   NSW   94534.0

In [38]:
len(t45_long)

207

In [39]:
t45_long["principal_diagnosis"].unique()

<StringArray>
[                                                          'A00–B99  Certain infectious and parasitic diseases',
                                                                                           'C00–D48  Neoplasms',
 'D50–D89  Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism',
                                                       'E00–E90  Endocrine, nutritional and metabolic diseases',
                                                                    'F00–F99  Mental and behavioural disorders',
                                                                      'G00–G99  Diseases of the nervous system',
                                                                      'H00–H59  Diseases of the eye and adnexa',
                                                             'H60–H95  Diseases of the ear and mastoid process',
                                                                  'I00–I99  Diseases of the circulatory system',
                                                                  'J00–J99  Diseases of the respiratory system',
                                                                    'K00–K93  Diseases of the digestive system',
                                                        'L00–L99  Diseases of the skin and subcutaneous tissue',
                                        'M00–M99  Diseases of the musculoskeletal system and connective tissue',
                                                                'N00–N99  Diseases of the genitourinary system',
                                                            'O00–O99  Pregnancy, childbirth and the puerperium',
                                              'P00–P96  Certain conditions originating in the perinatal period',
                                'Q00–Q99  Congenital malformations, deformations and chromosomal abnormalities',
             'R00–R99  Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified',
                                 'S00–T98  Injury, poisoning and certain other consequences of external causes',
                                       'U07.1, U07.2, and U07.7  Emergency use of codes U07.1, U07.2 and U07.7',
                                                          'U50–Y98  External causes of morbidity and mortality',
                                  'Z00–Z99  Factors influencing health status and contact with health services',
                                                                                           'Not stated/invalid']
Length: 23, dtype: str

In [40]:
t45_long = t45_long[
    ~t45_long["principal_diagnosis"].str.contains("Emergency use of codes|Not stated", na=False)
]

len(t45_long)

189

In [41]:
t45_long = t45_long[
    ~t45_long["principal_diagnosis"].str.contains("External causes", na=False)
]

len(t45_long)

180

In [42]:
t45_long = t45.melt(
    id_vars=["Principal diagnosis"],
    var_name="state",
    value_name="value"
)

t45_long = t45_long.rename(columns={
    "Principal diagnosis": "principal_diagnosis"
})

len(t45_long)

207

In [43]:
len(t45)

23

In [44]:
t45["Principal diagnosis"].tolist()

['A00–B99  Certain infectious and parasitic diseases',
 'C00–D48  Neoplasms',
 'D50–D89  Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism',
 'E00–E90  Endocrine, nutritional and metabolic diseases',
 'F00–F99  Mental and behavioural disorders',
 'G00–G99  Diseases of the nervous system',
 'H00–H59  Diseases of the eye and adnexa',
 'H60–H95  Diseases of the ear and mastoid process',
 'I00–I99  Diseases of the circulatory system',
 'J00–J99  Diseases of the respiratory system',
 'K00–K93  Diseases of the digestive system',
 'L00–L99  Diseases of the skin and subcutaneous tissue',
 'M00–M99  Diseases of the musculoskeletal system and connective tissue',
 'N00–N99  Diseases of the genitourinary system',
 'O00–O99  Pregnancy, childbirth and the puerperium',
 'P00–P96  Certain conditions originating in the perinatal period',
 'Q00–Q99  Congenital malformations, deformations and chromosomal abnormalities',
 'R00–R99  Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified',
 'S00–T98  Injury, poisoning and certain other consequences of external causes',
 'U07.1, U07.2, and U07.7  Emergency use of codes U07.1, U07.2 and U07.7',
 'U50–Y98  External causes of morbidity and mortality',
 'Z00–Z99  Factors influencing health status and contact with health services',
 'Not stated/invalid']

In [45]:
t45 = t45.drop(columns=["Total"])

In [46]:
t45_long = t45.melt(
    id_vars=["Principal diagnosis"],
    var_name="state",
    value_name="value"
)

t45_long = t45_long.rename(columns={
    "Principal diagnosis": "principal_diagnosis"
})

len(t45_long)

184

In [47]:
t49 = ed_data["Table 4.9"]

t49.head()

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
0,R10 \tAbdominal and pelvic pain,155163.0,110782.0,83426.0,37360.0,27294.0,8412.0,10123.0,6518.0,439078.0
1,R07 \tPain in throat and chest,142661.0,108508.0,85241.0,40933.0,25766.0,10107.0,9184.0,7794.0,430194.0
2,R69 \tUnknown and unspecified causes of morbidity,182306.0,50310.0,7403.0,1410.0,49778.0,8431.0,1176.0,396.0,301210.0
3,T14 \tInjury of unspecified body region,93369.0,6905.0,31766.0,12054.0,17128.0,106.0,1276.0,2373.0,164977.0
4,M54 \tDorsalgia,58542.0,37550.0,30648.0,12519.0,9504.0,4187.0,4040.0,2914.0,159904.0

In [48]:
t49["Principal diagnosis"] = (
    t49["Principal diagnosis"]
    .str.replace("\t", " ", regex=False)
    .str.strip()
)

t49["Principal diagnosis"].head()

0                      R10  Abdominal and pelvic pain
1                       R07  Pain in throat and chest
2    R69  Unknown and unspecified causes of morbidity
3              T14  Injury of unspecified body region
4                                      M54  Dorsalgia
Name: Principal diagnosis, dtype: str

In [49]:
t49.tail(10)

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
18,J06 Acute upper respiratory infections of mul...,41148.0,17781.0,15338.0,9709.0,8123.0,1919.0,1506.0,2424.0,97948.0
19,"J18 Pneumonia, organism unspecified",35824.0,15492.0,20395.0,10056.0,10806.0,1233.0,2624.0,863.0,97293.0
20,Other,1884622.0,1231723.0,1088983.0,684723.0,376659.0,125512.0,101059.0,118462.0,5611743.0
21,Missing/Not reported,39162.0,93590.0,110841.0,74720.0,13.0,72.0,3989.0,16763.0,339150.0
22,Total,3160473.0,1978267.0,1766839.0,1027017.0,622876.0,183120.0,167603.0,188117.0,9094312.0
23,(a) Presentations include all types of visit.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
t49 = t49[t49["NSW"].notna()]

In [51]:
t49.tail()

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
18,J06 Acute upper respiratory infections of mul...,41148.0,17781.0,15338.0,9709.0,8123.0,1919.0,1506.0,2424.0,97948.0
19,"J18 Pneumonia, organism unspecified",35824.0,15492.0,20395.0,10056.0,10806.0,1233.0,2624.0,863.0,97293.0
20,Other,1884622.0,1231723.0,1088983.0,684723.0,376659.0,125512.0,101059.0,118462.0,5611743.0
21,Missing/Not reported,39162.0,93590.0,110841.0,74720.0,13.0,72.0,3989.0,16763.0,339150.0
22,Total,3160473.0,1978267.0,1766839.0,1027017.0,622876.0,183120.0,167603.0,188117.0,9094312.0

In [52]:
t49 = t49[t49["Principal diagnosis"] != "Total"]

t49.tail()

,Principal diagnosis,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
17,S01 Open wound of head,32929.0,20293.0,17103.0,16625.0,7110.0,1636.0,1585.0,2373.0,99654.0
18,J06 Acute upper respiratory infections of mul...,41148.0,17781.0,15338.0,9709.0,8123.0,1919.0,1506.0,2424.0,97948.0
19,"J18 Pneumonia, organism unspecified",35824.0,15492.0,20395.0,10056.0,10806.0,1233.0,2624.0,863.0,97293.0
20,Other,1884622.0,1231723.0,1088983.0,684723.0,376659.0,125512.0,101059.0,118462.0,5611743.0
21,Missing/Not reported,39162.0,93590.0,110841.0,74720.0,13.0,72.0,3989.0,16763.0,339150.0

In [53]:
t49 = t49.drop(columns=["Total"])

t49.columns

Index(['Principal diagnosis', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT',
       'NT'],
      dtype='str')

In [54]:
t49_long = t49.melt(
    id_vars=["Principal diagnosis"],
    var_name="state",
    value_name="value"
)

t49_long.head()

                                Principal diagnosis state     value
0                    R10  Abdominal and pelvic pain   NSW  155163.0
1                     R07  Pain in throat and chest   NSW  142661.0
2  R69  Unknown and unspecified causes of morbidity   NSW  182306.0
3            T14  Injury of unspecified body region   NSW   93369.0
4                                    M54  Dorsalgia   NSW   58542.0

In [55]:
t49_long = t49_long.rename(columns={
    "Principal diagnosis": "principal_diagnosis"
})

t49_long.head()

                                principal_diagnosis state     value
0                    R10  Abdominal and pelvic pain   NSW  155163.0
1                     R07  Pain in throat and chest   NSW  142661.0
2  R69  Unknown and unspecified causes of morbidity   NSW  182306.0
3            T14  Injury of unspecified body region   NSW   93369.0
4                                    M54  Dorsalgia   NSW   58542.0

In [56]:
len(t49)

22

In [57]:
len(t49_long)

176

In [58]:
t51 = ed_data["Table 5.1"]
t51.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
0,NSW,Median waiting time (minutes),14.0000,14.0000,15.000,15.0000,15.0000
1,NSW,90th percentile waiting time (minutes),81.0000,89.0000,100.000,98.0000,104.0000
2,NSW,Proportion seen on time (%),79.1574,77.0933,74.023,74.3605,73.2518
3,Vic,Median waiting time (minutes),20.0000,22.0000,20.000,16.0000,15.0000
4,Vic,90th percentile waiting time (minutes),106.0000,118.0000,114.000,94.0000,91.0000

In [59]:
t51.tail(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
24,Total,Median waiting time (minutes),18.0000,20.0000,20.0000,18.00,18.0000
25,Total,90th percentile waiting time (minutes),102.0000,117.0000,124.0000,117.00,118.0000
26,Total,Proportion seen on time (%),70.7616,66.5476,64.9529,66.96,67.0905
27,Note: Median waiting time is equivalent to the...,NaN,NaN,NaN,NaN,NaN,NaN
28,(a) Data relate to presentations with a typ...,NaN,NaN,NaN,NaN,NaN,NaN
29,(b) Records were excluded from the calculat...,NaN,NaN,NaN,NaN,NaN,NaN
30,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN
31,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN
32,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN
33,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
t51 = t51[t51["2020–21"].notna()]

t51.tail()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
22,NT,90th percentile waiting time (minutes),117.0000,134.0000,161.0000,187.0000,176.0000
23,NT,Proportion seen on time (%),60.9322,57.1730,49.9830,47.3225,48.1880
24,Total,Median waiting time (minutes),18.0000,20.0000,20.0000,18.0000,18.0000
25,Total,90th percentile waiting time (minutes),102.0000,117.0000,124.0000,117.0000,118.0000
26,Total,Proportion seen on time (%),70.7616,66.5476,64.9529,66.9600,67.0905

In [61]:
t51 = t51[t51["State/territory"] != "Total"]

t51.tail()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
19,ACT,90th percentile waiting time (minutes),181.0000,203.0000,191.0000,124.0000,106.0000
20,ACT,Proportion seen on time (%),47.8750,48.2545,50.9122,61.6651,61.6724
21,NT,Median waiting time (minutes),27.0000,29.0000,38.0000,42.0000,37.0000
22,NT,90th percentile waiting time (minutes),117.0000,134.0000,161.0000,187.0000,176.0000
23,NT,Proportion seen on time (%),60.9322,57.1730,49.9830,47.3225,48.1880

In [62]:
t51_long = t51.melt(
    id_vars=["State/territory", "Measure"],
    var_name="year",
    value_name="value"
)

t51_long.head()

  State/territory                                 Measure     year     value
0             NSW           Median waiting time (minutes)  2020–21   14.0000
1             NSW  90th percentile waiting time (minutes)  2020–21   81.0000
2             NSW             Proportion seen on time (%)  2020–21   79.1574
3             Vic           Median waiting time (minutes)  2020–21   20.0000
4             Vic  90th percentile waiting time (minutes)  2020–21  106.0000

In [63]:
len(t51_long)

120

In [64]:
t51_long = t51_long.rename(columns={
    "State/territory": "state",
    "Measure": "measure"
})

t51_long.head()

  state                                 measure     year     value
0   NSW           Median waiting time (minutes)  2020–21   14.0000
1   NSW  90th percentile waiting time (minutes)  2020–21   81.0000
2   NSW             Proportion seen on time (%)  2020–21   79.1574
3   Vic           Median waiting time (minutes)  2020–21   20.0000
4   Vic  90th percentile waiting time (minutes)  2020–21  106.0000

In [65]:
t53 = ed_data["Table 5.3"]
t53.head()

,Peer group,Triage category,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
0,Principal referral and womens and children's h...,Resuscitation,99.9548,100.0000,99.9595,100,98.5025,99.537,99.115,100,99.7970
1,Principal referral and womens and children's h...,Emergency,74.9598,64.2770,74.9079,63.2382,49.6451,39.0862,62.7306,36.512,66.9975
2,Principal referral and womens and children's h...,Urgent,67.9040,72.3761,67.5799,21.7646,35.8249,27.6252,47.9112,18.0986,59.0583
3,Principal referral and womens and children's h...,Semi-urgent,73.1714,73.4373,76.8113,37.1478,54.1114,37.2238,64.3585,33.1376,66.3714
4,Principal referral and womens and children's h...,Non-urgent,86.9421,88.5196,91.6651,64.2091,77.8728,64.5833,87.0656,64.667,85.6263

In [66]:
t53.tail(10)

,Peer group,Triage category,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
32,All hospitals,Urgent,67.8571,69.1766,67.2104,29.4146,43.66,37.7792,51.2261,40.0083,61.0723
33,All hospitals,Semi-urgent,74.1231,75.7456,77.6974,46.9861,61.4072,52.3496,68.5805,47.9467,69.6998
34,All hospitals,Non-urgent,90.1395,90.6623,92.6397,80.4318,84.3354,74.2923,88.7337,82.2797,88.8603
35,All hospitals,Total,73.2518,71.5328,72.4388,45.5782,53.4049,46.0197,61.6724,48.188,67.0905
36,(a) Data relate to presentations with a ty...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,(b) Records were excluded from the calcula...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
t53 = t53[t53["NSW"].notna()]

In [68]:
t53.tail()

,Peer group,Triage category,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
31,All hospitals,Emergency,75.6227,63.9682,73.0111,66.5659,50.1697,46.8936,64.4283,49.1614,68.4090
32,All hospitals,Urgent,67.8571,69.1766,67.2104,29.4146,43.66,37.7792,51.2261,40.0083,61.0723
33,All hospitals,Semi-urgent,74.1231,75.7456,77.6974,46.9861,61.4072,52.3496,68.5805,47.9467,69.6998
34,All hospitals,Non-urgent,90.1395,90.6623,92.6397,80.4318,84.3354,74.2923,88.7337,82.2797,88.8603
35,All hospitals,Total,73.2518,71.5328,72.4388,45.5782,53.4049,46.0197,61.6724,48.188,67.0905

In [69]:
t53 = t53[t53["Triage category"] != "Total"]

t53.tail()

,Peer group,Triage category,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
30,All hospitals,Resuscitation,99.9512,100.0000,99.9584,99.8387,98.9319,99.5763,99.0253,98.4168,99.7993
31,All hospitals,Emergency,75.6227,63.9682,73.0111,66.5659,50.1697,46.8936,64.4283,49.1614,68.4090
32,All hospitals,Urgent,67.8571,69.1766,67.2104,29.4146,43.66,37.7792,51.2261,40.0083,61.0723
33,All hospitals,Semi-urgent,74.1231,75.7456,77.6974,46.9861,61.4072,52.3496,68.5805,47.9467,69.6998
34,All hospitals,Non-urgent,90.1395,90.6623,92.6397,80.4318,84.3354,74.2923,88.7337,82.2797,88.8603

In [70]:
t53 = t53.drop(columns=["Total"])

t53.columns

Index(['Peer group', 'Triage category', 'NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas',
       'ACT', 'NT'],
      dtype='str')

In [71]:
t53_long = t53.melt(
    id_vars=["Peer group", "Triage category"],
    var_name="state",
    value_name="value"
)

t53_long.head()

,Peer group,Triage category,state,value
0,Principal referral and womens and children's h...,Resuscitation,NSW,99.9548
1,Principal referral and womens and children's h...,Emergency,NSW,74.9598
2,Principal referral and womens and children's h...,Urgent,NSW,67.904
3,Principal referral and womens and children's h...,Semi-urgent,NSW,73.1714
4,Principal referral and womens and children's h...,Non-urgent,NSW,86.9421

In [72]:
t53_long = t53_long.rename(columns={
    "Peer group": "peer_group",
    "Triage category": "triage_category"
})

t53_long.head()

,peer_group,triage_category,state,value
0,Principal referral and womens and children's h...,Resuscitation,NSW,99.9548
1,Principal referral and womens and children's h...,Emergency,NSW,74.9598
2,Principal referral and womens and children's h...,Urgent,NSW,67.904
3,Principal referral and womens and children's h...,Semi-urgent,NSW,73.1714
4,Principal referral and womens and children's h...,Non-urgent,NSW,86.9421

In [73]:
len(t51_long)

120

In [75]:
t53_long.head()

,peer_group,triage_category,state,value
0,Principal referral and womens and children's h...,Resuscitation,NSW,99.9548
1,Principal referral and womens and children's h...,Emergency,NSW,74.9598
2,Principal referral and womens and children's h...,Urgent,NSW,67.904
3,Principal referral and womens and children's h...,Semi-urgent,NSW,73.1714
4,Principal referral and womens and children's h...,Non-urgent,NSW,86.9421

In [76]:
t61 = ed_data["Table 6.1"]
t61.head()

,Admission status,State/territory,2020–21,2021–22,2022–23,2023–24,2024–25
0,Patient subsequently admitted(c),NSW,15:25,17:55,20:53,20:30,20:40
1,Patient subsequently admitted(c),Vic,12:46,16:10,18:55,17:43,17:47
2,Patient subsequently admitted(c),Qld,10:21,12:22,14:44,16:11,18:03
3,Patient subsequently admitted(c),WA,10:59,13:11,15:42,15:55,19:09
4,Patient subsequently admitted(c),SA,12:46,15:06,18:06,19:05,20:16

In [77]:
t63 = ed_data["Table 6.3"]
t63.head()

,Admission status(b),State/territory,2020–21,2021–22,2022–23,2023–24,2024–25
0,All presentations to emergency departments,NSW,68.9650,64.2372,58.6348,57.4209,56.3124
1,All presentations to emergency departments,Vic,61.9723,55.3146,51.9815,53.2019,52.6708
2,All presentations to emergency departments,Qld,69.1127,61.3550,53.9983,51.8571,49.9313
3,All presentations to emergency departments,WA,70.6972,64.5944,60.4344,59.1479,53.9310
4,All presentations to emergency departments,SA,60.7775,57.5591,51.9749,50.7770,49.6229

In [78]:
t63.tail(10)

,Admission status(b),State/territory,2020–21,2021–22,2022–23,2023–24,2024–25
14,Patient subsequently admitted,Tas,23.3189,24.5344,22.0342,20.6608,20.4710
15,Patient subsequently admitted,ACT,37.7422,32.9806,32.1184,43.3492,48.6886
16,Patient subsequently admitted,NT,32.0501,27.4266,39.7813,28.9395,29.1620
17,Patient subsequently admitted,Total,41.8051,34.4408,30.7449,30.7951,30.0858
18,(a) Includes presentations for all types o...,NaN,NaN,NaN,NaN,NaN,NaN
19,(b) Patient subsequently admitted is where...,NaN,NaN,NaN,NaN,NaN,NaN
20,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN
21,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN
22,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN
23,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
t63 = t63[t63["2020–21"].notna()]

t63.tail()

,Admission status(b),State/territory,2020–21,2021–22,2022–23,2023–24,2024–25
13,Patient subsequently admitted,SA,42.2457,39.1044,32.3177,29.7894,27.8981
14,Patient subsequently admitted,Tas,23.3189,24.5344,22.0342,20.6608,20.4710
15,Patient subsequently admitted,ACT,37.7422,32.9806,32.1184,43.3492,48.6886
16,Patient subsequently admitted,NT,32.0501,27.4266,39.7813,28.9395,29.1620
17,Patient subsequently admitted,Total,41.8051,34.4408,30.7449,30.7951,30.0858

In [80]:
t63 = t63.drop(columns=["Admission status(b)"])

t63.columns

Index(['State/territory', '2020–21', '2021–22', '2022–23', '2023–24',
       '2024–25'],
      dtype='str')

In [81]:
t63_long = t63.melt(
    id_vars=["State/territory"],
    var_name="year",
    value_name="value"
)

t63_long.head()

  State/territory     year    value
0             NSW  2020–21  68.9650
1             Vic  2020–21  61.9723
2             Qld  2020–21  69.1127
3              WA  2020–21  70.6972
4              SA  2020–21  60.7775

In [82]:
t63_long = t63_long.rename(columns={
    "State/territory": "state"
})

t63_long.head()

  state     year    value
0   NSW  2020–21  68.9650
1   Vic  2020–21  61.9723
2   Qld  2020–21  69.1127
3    WA  2020–21  70.6972
4    SA  2020–21  60.7775

In [83]:
len(t63_long)

90

In [84]:
t63_long["state"].unique()

<StringArray>
['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total']
Length: 9, dtype: str

In [85]:
t63_long = t63_long[t63_long["state"] != "Total"]

len(t63_long)

80

In [86]:
t22_long.to_csv("ed_presentations.csv", index=False)
t31_long.to_csv("ed_demographics.csv", index=False)
t45_long.to_csv("ed_diagnosis_groups.csv", index=False)
t49_long.to_csv("ed_top_diagnoses.csv", index=False)
t51_long.to_csv("ed_waiting_times.csv", index=False)
t53_long.to_csv("ed_triage_performance.csv", index=False)
t63_long.to_csv("ed_length_of_stay.csv", index=False)