In [1]:
import pandas as pd

elective_file = "../data/raw/Elective_Filtered.xlsx"

elective_data = pd.read_excel(
    elective_file,
    sheet_name=None
)

In [2]:
elective_data.keys()

dict_keys(['Table 2.1', 'Table 2.4', 'Table 3.1', 'Table 3.2', 'Table 4.1', 'Table 4.2', 'Table 4.4', 'Table 4.10'])

In [4]:
t24 = elective_data["Table 2.4"].copy()
t31 = elective_data["Table 3.1"].copy()
t42 = elective_data["Table 4.2"].copy()
t410 = elective_data["Table 4.10"].copy()

In [7]:
t24.tail(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25(b),Average annual change (%) last five years(a),Change (%) since last year(a)
14,NT,Admissions,7746.000000,6712.000000,7170.000000,6915.000000,6406.000000,-4.6,-7.36
15,NT,"Admissions per 1,000 population(b)",31.306077,27.048047,28.328724,26.853535,24.559117,-5.9,-8.54
16,Total,Admissions,754600.000000,622988.000000,735460.000000,778466.000000,790528.000000,1.2,1.55
17,Total,"Admissions per 1,000 population(b)",29.419966,24.254546,28.266570,29.199860,29.066936,-0.3,-0.46
18,(a) Interpretation of changes from 2019–20 on...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,(b) Crude rates are based on the estimated re...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
t24.head(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25(b),Average annual change (%) last five years(a),Change (%) since last year(a)
0,NSW,Admissions,251001.000000,182808.000000,225749.000000,231804.000000,232849.000000,-1.9,0.45
1,NSW,"Admissions per 1,000 population(b)",30.947241,22.577078,27.590601,27.739740,27.416772,-3.0,-1.16
2,Vic,Admissions,164155.000000,147792.000000,190867.000000,210677.000000,211961.000000,6.6,0.61
3,Vic,"Admissions per 1,000 population(b)",24.815398,22.571169,28.852654,30.994816,30.483783,5.3,-1.65
4,Qld,Admissions,148272.000000,127599.000000,140977.000000,149420.000000,149195.000000,0.2,-0.15
5,Qld,"Admissions per 1,000 population(b)",28.703660,24.463871,26.544817,27.415332,26.777881,-1.7,-2.33
6,WA,Admissions,92410.000000,70988.000000,80793.000000,85991.000000,89614.000000,-0.8,4.21
7,WA,"Admissions per 1,000 population(b)",34.063029,25.819780,28.917290,29.745038,30.099184,-3.0,1.19
8,SA,Admissions,57355.000000,52742.000000,55900.000000,56484.000000,61419.000000,1.7,8.74
9,SA,"Admissions per 1,000 population(b)",32.035546,29.258832,30.630657,30.406224,32.624371,0.5,7.30

In [9]:
t24["Measure"].unique()

array(['Admissions', 'Admissions per 1,000 population(b)', nan],
      dtype=object)

In [10]:
t24["State/territory"].unique()

array(['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total',
       '(a)\xa0\xa0Interpretation of changes from 2019–20 onwards should take into account the impacts of the cancellation of Urgency category 3 and restrictions on Urgency category 2 elective surgery in March 2020 and ongoing restrictions in some jurisdictions during 2020–21 and 2021–22 due to COVID-19. Interpretation of changes over time in earlier years should take into account changes in coverage as noted in Appendix A.',
       '(b)  Crude rates are based on the estimated resident population as at 30 June at the beginning of the reference period.',
       'Note: Appendix information with notes on definitions and data limitations is available to download at the link below:',
       'https://www.aihw.gov.au/hospitals/other-resources/about-the-data',
       'Technical specifications', 'Back to contents'], dtype=object)

In [12]:
t24_clean = t24.copy()

# Remove rows where measure is missing
t24_clean = t24_clean[t24_clean["Measure"].notna()]

# Remove Total rows
t24_clean = t24_clean[t24_clean["State/territory"] != "Total"]

# Drop derived columns
t24_clean = t24_clean.drop(columns=[
    "Average annual change (%) last five years(a)",
    "Change (%) since last year(a)"
])

t24_clean.head(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25(b)
0,NSW,Admissions,251001.000000,182808.000000,225749.000000,231804.000000,232849.000000
1,NSW,"Admissions per 1,000 population(b)",30.947241,22.577078,27.590601,27.739740,27.416772
2,Vic,Admissions,164155.000000,147792.000000,190867.000000,210677.000000,211961.000000
3,Vic,"Admissions per 1,000 population(b)",24.815398,22.571169,28.852654,30.994816,30.483783
4,Qld,Admissions,148272.000000,127599.000000,140977.000000,149420.000000,149195.000000
5,Qld,"Admissions per 1,000 population(b)",28.703660,24.463871,26.544817,27.415332,26.777881
6,WA,Admissions,92410.000000,70988.000000,80793.000000,85991.000000,89614.000000
7,WA,"Admissions per 1,000 population(b)",34.063029,25.819780,28.917290,29.745038,30.099184
8,SA,Admissions,57355.000000,52742.000000,55900.000000,56484.000000,61419.000000
9,SA,"Admissions per 1,000 population(b)",32.035546,29.258832,30.630657,30.406224,32.624371

In [13]:
t24_clean["State/territory"].unique()

array(['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT'], dtype=object)

In [14]:
t24_clean["Measure"].unique()

array(['Admissions', 'Admissions per 1,000 population(b)'], dtype=object)

In [16]:
t24_clean.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25(b)
0,NSW,Admissions,251001.000000,182808.000000,225749.000000,231804.000000,232849.000000
1,NSW,"Admissions per 1,000 population(b)",30.947241,22.577078,27.590601,27.739740,27.416772
2,Vic,Admissions,164155.000000,147792.000000,190867.000000,210677.000000,211961.000000
3,Vic,"Admissions per 1,000 population(b)",24.815398,22.571169,28.852654,30.994816,30.483783
4,Qld,Admissions,148272.000000,127599.000000,140977.000000,149420.000000,149195.000000

In [17]:
t24_clean.shape

(16, 7)

In [18]:
years = ["2020–21","2021–22","2022–23","2023–24","2024–25(b)"]

t24_long = t24_clean.melt(
    id_vars=["State/territory","Measure"],
    value_vars=years,
    var_name="year",
    value_name="value"
)

t24_long.head()

  State/territory                             Measure     year          value
0             NSW                          Admissions  2020–21  251001.000000
1             NSW  Admissions per 1,000 population(b)  2020–21      30.947241
2             Vic                          Admissions  2020–21  164155.000000
3             Vic  Admissions per 1,000 population(b)  2020–21      24.815398
4             Qld                          Admissions  2020–21  148272.000000

In [19]:
t24_long.shape

(80, 4)

In [20]:
t24_long = t24_long.rename(columns={
    "State/territory": "state",
    "Measure": "metric"
})

In [21]:
t24_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   80 non-null     object
 1   metric  80 non-null     object
 2   year    80 non-null     object
 3   value   80 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.6+ KB

In [22]:
t24_long["metric"].value_counts()

metric
Admissions                            40
Admissions per 1,000 population(b)    40
Name: count, dtype: int64

In [23]:
t24_long["metric"] = t24_long["metric"].str.replace("(b)", "", regex=False)

In [24]:
t24_long["metric"].unique()

array(['Admissions', 'Admissions per 1,000 population'], dtype=object)

In [25]:
t24_long = t24_long.sort_values(["state","metric","year"])

In [26]:
t24_long = t24_long.reset_index(drop=True)

In [27]:
t24_long.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   state   80 non-null     object
 1   metric  80 non-null     object
 2   year    80 non-null     object
 3   value   80 non-null     float64
dtypes: float64(1), object(3)
memory usage: 2.6+ KB

In [28]:
t24_long.to_csv("elective_admissions.csv", index=False)

In [29]:
t31.head(10)

,Surgical specialty,2020–21,2021–22,2022–23,2023–24,2024–25(b),Average annual change (%) last five years(a),Change (%) since last year(a)
0,Cardio-thoracic surgery,10993.0,9834.0,11063.0,11710.0,12022.0,2.3,2.66
1,"Otolaryngology, head and neck surgery",58776.0,44894.0,56934.0,61720.0,60031.0,0.5,-2.74
2,General surgery,154677.0,127733.0,149234.0,155124.0,155126.0,0.1,0.00
3,Gynaecology surgery,90169.0,75625.0,87021.0,90442.0,94148.0,1.1,4.10
4,Neurosurgery,12757.0,10513.0,12531.0,13559.0,12867.0,0.2,-5.10
5,Ophthalmology surgery,100653.0,81904.0,102122.0,111231.0,117596.0,4.0,5.72
6,Orthopaedic surgery,108361.0,83198.0,101442.0,105495.0,103750.0,-1.1,-1.65
7,Plastic and reconstructive surgery,58350.0,53067.0,62161.0,65807.0,67252.0,3.6,2.20
8,Urological surgery,114820.0,96644.0,107339.0,113979.0,116931.0,0.5,2.59
9,Vascular surgery,17471.0,15252.0,16885.0,19218.0,18750.0,1.8,-2.44

In [30]:
t31.shape

(20, 8)

In [31]:
t31.columns

Index(['Surgical specialty', '2020–21', '2021–22', '2022–23', '2023–24',
       '2024–25(b)', 'Average annual change (%) last five years(a)',
       'Change (%) since last year(a)'],
      dtype='object')

In [32]:
t31["Surgical specialty"].unique()

array(['Cardio-thoracic surgery', 'Otolaryngology, head and neck surgery',
       'General surgery', 'Gynaecology surgery', 'Neurosurgery',
       'Ophthalmology surgery', 'Orthopaedic surgery',
       'Plastic and reconstructive surgery', 'Urological surgery',
       'Vascular surgery', 'Paediatric surgery(b)', 'Other', 'Total(c)',
       '(a)\xa0\xa0 Interpretation of changes from 2019–20 onwards should take into account the impacts of the cancellation of Urgency category 3 and restrictions on Urgency category 2 elective surgery in March 2020 and ongoing restrictions in some jurisdictions during 2020–21 and 2021–22 due to COVID-19. Interpretation of changes over time in earlier years should take into account changes in coverage as noted in Appendix A.',
       '(b)\xa0  From 2020–21 to 2024–25 Paediatric surgery was not reported for Queensland and the Northern Territory. Paediatric surgery was not reported for Victoria in 2020–21. These differences in reporting should be taken into consideration when comparing these data over time.',
       '(c)\xa0\xa0\xa0 Includes admissions for which the Surgical specialty was not reported.',
       'Note: Appendix information with notes on definitions and data limitations is available to download at the link below:',
       'https://www.aihw.gov.au/hospitals/other-resources/about-the-data',
       'Technical specifications', 'Back to contents'], dtype=object)

In [33]:
t31.tail(10)

,Surgical specialty,2020–21,2021–22,2022–23,2023–24,2024–25(b),Average annual change (%) last five years(a),Change (%) since last year(a)
10,Paediatric surgery(b),8906.0,8136.0,10205.0,10458.0,10504.0,4.2,0.44
11,Other,18667.0,16188.0,18523.0,19723.0,21551.0,3.7,9.27
12,Total(c),754600.0,622988.0,735460.0,778466.0,790528.0,1.2,1.55
13,(a) Interpretation of changes from 2019–20 o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,(b) From 2020–21 to 2024–25 Paediatric surge...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,(c) Includes admissions for which the Surgi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
t31_clean = t31.copy()

# remove rows with missing values (footnotes)
t31_clean = t31_clean.dropna(subset=["2020–21"])

# remove total row
t31_clean = t31_clean[~t31_clean["Surgical specialty"].str.contains("Total", na=False)]

# drop derived columns
t31_clean = t31_clean.drop(columns=[
    "Average annual change (%) last five years(a)",
    "Change (%) since last year(a)"
])

t31_clean.head()

,Surgical specialty,2020–21,2021–22,2022–23,2023–24,2024–25(b)
0,Cardio-thoracic surgery,10993.0,9834.0,11063.0,11710.0,12022.0
1,"Otolaryngology, head and neck surgery",58776.0,44894.0,56934.0,61720.0,60031.0
2,General surgery,154677.0,127733.0,149234.0,155124.0,155126.0
3,Gynaecology surgery,90169.0,75625.0,87021.0,90442.0,94148.0
4,Neurosurgery,12757.0,10513.0,12531.0,13559.0,12867.0

In [35]:
t31_clean.shape

(12, 6)

In [36]:
t31_clean["Surgical specialty"].unique()

array(['Cardio-thoracic surgery', 'Otolaryngology, head and neck surgery',
       'General surgery', 'Gynaecology surgery', 'Neurosurgery',
       'Ophthalmology surgery', 'Orthopaedic surgery',
       'Plastic and reconstructive surgery', 'Urological surgery',
       'Vascular surgery', 'Paediatric surgery(b)', 'Other'], dtype=object)

In [37]:
t31_clean.head()

,Surgical specialty,2020–21,2021–22,2022–23,2023–24,2024–25(b)
0,Cardio-thoracic surgery,10993.0,9834.0,11063.0,11710.0,12022.0
1,"Otolaryngology, head and neck surgery",58776.0,44894.0,56934.0,61720.0,60031.0
2,General surgery,154677.0,127733.0,149234.0,155124.0,155126.0
3,Gynaecology surgery,90169.0,75625.0,87021.0,90442.0,94148.0
4,Neurosurgery,12757.0,10513.0,12531.0,13559.0,12867.0

In [38]:
years = ["2020–21","2021–22","2022–23","2023–24","2024–25(b)"]

t31_long = t31_clean.melt(
    id_vars=["Surgical specialty"],
    value_vars=years,
    var_name="year",
    value_name="value"
)

t31_long.head()

                      Surgical specialty     year     value
0                Cardio-thoracic surgery  2020–21   10993.0
1  Otolaryngology, head and neck surgery  2020–21   58776.0
2                        General surgery  2020–21  154677.0
3                    Gynaecology surgery  2020–21   90169.0
4                           Neurosurgery  2020–21   12757.0

In [39]:
t31_long = t31_long.rename(columns={
    "Surgical specialty": "surgical_specialty"
})

In [40]:
t31_long["year"] = t31_long["year"].str.replace("(b)", "", regex=False)

In [41]:
t31_long["surgical_specialty"] = t31_long["surgical_specialty"].str.replace("(b)", "", regex=False)

In [43]:
t31_long.shape

(60, 3)

In [44]:
t31_long.head()

                      surgical_specialty     year     value
0                Cardio-thoracic surgery  2020–21   10993.0
1  Otolaryngology, head and neck surgery  2020–21   58776.0
2                        General surgery  2020–21  154677.0
3                    Gynaecology surgery  2020–21   90169.0
4                           Neurosurgery  2020–21   12757.0

In [45]:
t31_long.to_csv("elective_surgical_specialty.csv", index=False)

In [46]:
t42.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
0,NSW,Days waited at the 50th percentile,68.0000,55.0000,69.000,65.0000,69.0000
1,NSW,Days waited at the 90th percentile,375.0000,363.0000,400.000,356.0000,363.0000
2,NSW,Percentage waited more than 365 days,11.3681,9.5652,12.995,7.8295,9.1772
3,Vic,Days waited at the 50th percentile,28.0000,25.0000,36.000,33.0000,28.0000
4,Vic,Days waited at the 90th percentile,266.0000,254.0000,357.000,281.0000,205.0000

In [47]:
t42.tail(10)

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
22,NT,Days waited at the 90th percentile,276.0000,288.0000,321.0000,334.0000,328.0000
23,NT,Percentage waited more than 365 days,6.7261,7.2408,8.8285,8.4888,8.1642
24,Total,Days waited at the 50th percentile,48.0000,40.0000,49.0000,46.0000,45.0000
25,Total,Days waited at the 90th percentile,348.0000,323.0000,361.0000,329.0000,329.0000
26,Total,Percentage waited more than 365 days,7.5735,6.2717,9.5703,6.3815,5.9564
27,(a) Interpretation of changes from 2019–20 o...,NaN,NaN,NaN,NaN,NaN,NaN
28,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN
29,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN
30,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN
31,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
t42["Measure"].unique()

array(['Days waited at the 50th percentile',
       'Days waited at the 90th percentile',
       'Percentage waited more than 365 days', nan], dtype=object)

In [49]:
t42["State/territory"].unique()

array(['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT', 'Total',
       '(a)\xa0\xa0 Interpretation of changes from 2019–20 onwards should take into account the impacts of the cancellation of Urgency category 3 and restrictions on Urgency category 2 elective surgery in March 2020 and ongoing restrictions in some jurisdictions during 2020–21 and 2021–22 due to COVID-19. Interpretation of changes over time in earlier years should take into account changes in coverage as noted in Appendix A.',
       'Note: Appendix information with notes on definitions and data limitations is available to download at the link below:',
       'https://www.aihw.gov.au/hospitals/other-resources/about-the-data',
       'Technical specifications', 'Back to contents'], dtype=object)

In [50]:
t42_clean = t42.copy()

# remove rows where measure is missing
t42_clean = t42_clean[t42_clean["Measure"].notna()]

# remove total rows
t42_clean = t42_clean[t42_clean["State/territory"] != "Total"]

# remove footnote rows (they appear as NaN values)
t42_clean = t42_clean.dropna(subset=["2020–21"])

t42_clean.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
0,NSW,Days waited at the 50th percentile,68.0000,55.0000,69.000,65.0000,69.0000
1,NSW,Days waited at the 90th percentile,375.0000,363.0000,400.000,356.0000,363.0000
2,NSW,Percentage waited more than 365 days,11.3681,9.5652,12.995,7.8295,9.1772
3,Vic,Days waited at the 50th percentile,28.0000,25.0000,36.000,33.0000,28.0000
4,Vic,Days waited at the 90th percentile,266.0000,254.0000,357.000,281.0000,205.0000

In [51]:
t42_clean.shape

(24, 7)

In [52]:
t42_clean["State/territory"].unique()

array(['NSW', 'Vic', 'Qld', 'WA', 'SA', 'Tas', 'ACT', 'NT'], dtype=object)

In [53]:
t42_clean.head()

,State/territory,Measure,2020–21,2021–22,2022–23,2023–24,2024–25
0,NSW,Days waited at the 50th percentile,68.0000,55.0000,69.000,65.0000,69.0000
1,NSW,Days waited at the 90th percentile,375.0000,363.0000,400.000,356.0000,363.0000
2,NSW,Percentage waited more than 365 days,11.3681,9.5652,12.995,7.8295,9.1772
3,Vic,Days waited at the 50th percentile,28.0000,25.0000,36.000,33.0000,28.0000
4,Vic,Days waited at the 90th percentile,266.0000,254.0000,357.000,281.0000,205.0000

In [54]:
years = ["2020–21","2021–22","2022–23","2023–24","2024–25"]

t42_long = t42_clean.melt(
    id_vars=["State/territory","Measure"],
    value_vars=years,
    var_name="year",
    value_name="value"
)

t42_long.head()

  State/territory                               Measure     year     value
0             NSW    Days waited at the 50th percentile  2020–21   68.0000
1             NSW    Days waited at the 90th percentile  2020–21  375.0000
2             NSW  Percentage waited more than 365 days  2020–21   11.3681
3             Vic    Days waited at the 50th percentile  2020–21   28.0000
4             Vic    Days waited at the 90th percentile  2020–21  266.0000

In [55]:
t42_long.shape

(120, 4)

In [56]:
t42_long = t42_long.rename(columns={
    "State/territory": "state",
    "Measure": "metric"
})

In [57]:
t42_long = t42_long.sort_values(["state","metric","year"])
t42_long = t42_long.reset_index(drop=True)

In [58]:
t42_long.to_csv("elective_wait_times.csv", index=False)

In [59]:
t410.head()

,Clinical urgency,Measure,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
0,Category 1,Admissions,52066.0000,73516.0000,61806.0000,28208.0000,20150.0000,9858.0000,6926.000,2729.0000,255259.0000
1,Category 2,Admissions,90168.0000,89984.0000,57371.0000,30495.0000,24473.0000,7981.0000,5149.000,2526.0000,308147.0000
2,Category 3,Admissions,90615.0000,48461.0000,30018.0000,30911.0000,16796.0000,4680.0000,4490.000,1151.0000,227122.0000
3,Total,Admissions,232849.0000,211961.0000,149195.0000,89614.0000,61419.0000,22519.0000,16565.000,6406.0000,790528.0000
4,Category 1,Per cent of admissions,22.3604,34.6837,41.4263,31.4772,32.8074,43.7764,41.811,42.6007,32.2897

In [60]:
t410.shape

(13, 11)

In [61]:
t410.tail(10)

,Clinical urgency,Measure,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Total
3,Total,Admissions,232849.0000,211961.0000,149195.0000,89614.0000,61419.0000,22519.0000,16565.0000,6406.0000,790528.0000
4,Category 1,Per cent of admissions,22.3604,34.6837,41.4263,31.4772,32.8074,43.7764,41.8110,42.6007,32.2897
5,Category 2,Per cent of admissions,38.7238,42.4531,38.4537,34.0293,39.8460,35.4412,31.0836,39.4318,38.9799
6,Category 3,Per cent of admissions,38.9158,22.8632,20.1200,34.4935,27.3466,20.7825,27.1053,17.9675,28.7304
7,Total,Per cent of admissions,100.0000,100.0000,100.0000,100.0000,100.0000,100.0000,100.0000,100.0000,100.0000
8,Category 1—within 30 days; Category 2—within 9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Note: Appendix information with notes on defin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,https://www.aihw.gov.au/hospitals/other-resour...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Technical specifications,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Back to contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
t410_clean = t410.copy()

# remove total row
t410_clean = t410_clean[t410_clean["Clinical urgency"] != "Total"]

# drop total column
t410_clean = t410_clean.drop(columns=["Total"])

t410_clean.head()

,Clinical urgency,Measure,NSW,Vic,Qld,WA,SA,Tas,ACT,NT
0,Category 1,Admissions,52066.0000,73516.0000,61806.0000,28208.0000,20150.0000,9858.0000,6926.0000,2729.0000
1,Category 2,Admissions,90168.0000,89984.0000,57371.0000,30495.0000,24473.0000,7981.0000,5149.0000,2526.0000
2,Category 3,Admissions,90615.0000,48461.0000,30018.0000,30911.0000,16796.0000,4680.0000,4490.0000,1151.0000
4,Category 1,Per cent of admissions,22.3604,34.6837,41.4263,31.4772,32.8074,43.7764,41.8110,42.6007
5,Category 2,Per cent of admissions,38.7238,42.4531,38.4537,34.0293,39.8460,35.4412,31.0836,39.4318

In [63]:
t410_clean.shape

(11, 10)

In [64]:
t410_clean["Clinical urgency"].unique()

array(['Category 1', 'Category 2', 'Category 3',
       'Category 1—within 30 days; Category 2—within 90 days; Category 3—within 365 days.',
       'Note: Appendix information with notes on definitions and data limitations is available to download at the link below:',
       'https://www.aihw.gov.au/hospitals/other-resources/about-the-data',
       'Technical specifications', 'Back to contents'], dtype=object)

In [65]:
t410_clean = t410_clean[
    t410_clean["Clinical urgency"].isin([
        "Category 1",
        "Category 2",
        "Category 3"
    ])
]

In [66]:
t410_clean["Clinical urgency"].unique()

array(['Category 1', 'Category 2', 'Category 3'], dtype=object)

In [67]:
t410_clean.shape

(6, 10)

In [68]:
states = ["NSW","Vic","Qld","WA","SA","Tas","ACT","NT"]

t410_long = t410_clean.melt(
    id_vars=["Clinical urgency","Measure"],
    value_vars=states,
    var_name="state",
    value_name="value"
)

In [69]:
t410_long = t410_long.rename(columns={
    "Clinical urgency": "clinical_urgency",
    "Measure": "metric"
})

In [70]:
t410_long.shape

(48, 4)

In [71]:
t410_long.head()

  clinical_urgency                  metric state       value
0       Category 1              Admissions   NSW  52066.0000
1       Category 2              Admissions   NSW  90168.0000
2       Category 3              Admissions   NSW  90615.0000
3       Category 1  Per cent of admissions   NSW     22.3604
4       Category 2  Per cent of admissions   NSW     38.7238

In [72]:
t410_long.to_csv("elective_clinical_urgency.csv", index=False)