In [1]:
import pandas as pd

expenditure_data = pd.read_excel(
    "../data/raw/Expenditure_Filtered.xlsx",
    sheet_name=None
)

In [2]:
expenditure_data.keys()

dict_keys(['Table 3', 'Table 4', 'Table 5', 'Table 28', 'Table 29', 'Table 30', 'Table A3', 'Table B3', 'Table B6', 'Table B9', 'Table B12', 'Table B15', 'Table B18', 'Table B21', 'Table B24'])

In [3]:
t3 = expenditure_data["Table 3"]
t4 = expenditure_data["Table 4"]
t5 = expenditure_data["Table 5"]
t28 = expenditure_data["Table 28"]
t29 = expenditure_data["Table 29"]
t30 = expenditure_data["Table 30"]

In [4]:
t3.head()

,Unnamed: 0,Amount ($),Unnamed: 2,Unnamed: 3,Annual change in spending (%),Unnamed: 5
0,Year,Current,Constant,NaN,Nominal change,Real growth
1,2013–14,6608.756533,8509.998967,NaN,. .,. .
2,2014–15,6801.533849,8615.419165,NaN,2.916998,1.23878
3,2015–16,7057.752875,8773.923652,NaN,3.767077,1.839777
4,2016–17,7379.930619,8972.751459,NaN,4.564877,2.266122

In [5]:
t3.tail()

,Unnamed: 0,Amount ($),Unnamed: 2,Unnamed: 3,Annual change in spending (%),Unnamed: 5
17,(a) Based on annual estimated resident popul...,NaN,NaN,NaN,NaN,NaN
18,(b) Constant price health spending is in 202...,NaN,NaN,NaN,NaN,NaN
19,"Note: For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN
20,"Sources: AIHW Health Expenditure Database, Aus...",NaN,NaN,NaN,NaN,NaN
21,Link to Contents,NaN,NaN,NaN,NaN,NaN

In [6]:
t3.columns = t3.iloc[0]
t3 = t3.drop(0).reset_index(drop=True)

t3.head()

0     Year      Current     Constant  NaN Nominal change Real growth
0  2013–14  6608.756533  8509.998967  NaN            . .         . .
1  2014–15  6801.533849  8615.419165  NaN       2.916998     1.23878
2  2015–16  7057.752875  8773.923652  NaN       3.767077    1.839777
3  2016–17  7379.930619  8972.751459  NaN       4.564877    2.266122
4  2017–18   7494.46283  8953.393931  NaN       1.551942   -0.215737

In [7]:
t3 = t3.dropna(axis=1, how="all")

In [8]:
t3 = t3.rename(columns={
    "Year": "year",
    "Current": "spending_current",
    "Constant": "spending_constant",
    "Nominal change": "nominal_change_pct",
    "Real growth": "real_growth_pct"
})

t3.head()

0     year spending_current spending_constant Nominal change Real growth
0  2013–14      6608.756533       8509.998967            . .         . .
1  2014–15      6801.533849       8615.419165       2.916998     1.23878
2  2015–16      7057.752875       8773.923652       3.767077    1.839777
3  2016–17      7379.930619       8972.751459       4.564877    2.266122
4  2017–18       7494.46283       8953.393931       1.551942   -0.215737

In [9]:
t3 = t3[t3["year"].str.contains(r"\d{4}", na=False)]

In [10]:
cols = [
    "spending_current",
    "spending_constant",
    "nominal_change_pct",
    "real_growth_pct"
]

t3[cols] = t3[cols].apply(pd.to_numeric, errors="coerce")

KeyError: "['nominal_change_pct', 'real_growth_pct'] not in index"

In [11]:
t3.columns

Index(['year', 'spending_current', 'spending_constant', 'Nominal change',
       'Real growth'],
      dtype='object', name=0)

In [12]:
t3 = t3.rename(columns={
    "Nominal change": "nominal_change_pct",
    "Real growth": "real_growth_pct"
})

In [13]:
cols = [
    "spending_current",
    "spending_constant",
    "nominal_change_pct",
    "real_growth_pct"
]

t3[cols] = t3[cols].apply(pd.to_numeric, errors="coerce")

KeyError: "['nominal_change_pct', 'real_growth_pct'] not in index"

In [14]:
t3.keys

<bound method NDFrame.keys of 0                                                year spending_current  \
0                                             2013–14      6608.756533
1                                             2014–15      6801.533849
2                                             2015–16      7057.752875
3                                             2016–17      7379.930619
4                                             2017–18       7494.46283
5                                             2018–19      7819.655341
6                                             2019–20      8004.654783
7                                             2020–21      8725.989586
8                                             2021–22      9503.262635
9                                             2022–23      9693.700345
10                                            2023–24     10036.919659
12                                 2013–14 to 2018–19              . .
13                                 2018–19 to 2023–24              . .
14                                 2013–14 to 2023–24              . .
17  (b)   Constant price health spending is in 202...              NaN
18  Note: For more information about concepts, def...              NaN
19  Sources: AIHW Health Expenditure Database, Aus...              NaN

0  spending_constant Nominal change Real growth
0        8509.998967            . .         . .
1        8615.419165       2.916998     1.23878
2        8773.923652       3.767077    1.839777
3        8972.751459       4.564877    2.266122
4        8953.393931       1.551942   -0.215737
5        9163.986294       4.339104    2.352095
6        9191.120211       2.365826    0.296093
7        9821.941603       9.011442    6.863379
8       10389.573549       8.907563    5.779223
9       10171.191944       2.003919    -2.10193
10      10036.919659       3.540643   -1.320123
12               . .       3.422152    1.491807
13               . .       5.119326    1.836439
14               . .       4.267286    1.663977
17               NaN            NaN         NaN
18               NaN            NaN         NaN
19               NaN            NaN         NaN  >

In [18]:
t3.columns

Index(['year', 'spending_current', 'spending_constant', 'Nominal change',
       'Real growth'],
      dtype='object', name=0)

In [16]:
t3 = t3.rename(columns={
    "Nominal change": "nominal_change_pct",
    "Real growth": "real_growth_pct"
})

In [19]:
print([repr(col) for col in t3.columns])

["'year'", "'spending_current'", "'spending_constant'", "'Nominal\\xa0change'", "'Real\\xa0growth'"]

In [20]:
t3.columns = t3.columns.str.replace("\xa0", " ")

In [21]:
t3 = t3.rename(columns={
    "Nominal change": "nominal_change_pct",
    "Real growth": "real_growth_pct"
})

In [22]:
cols = [
    "spending_current",
    "spending_constant",
    "nominal_change_pct",
    "real_growth_pct"
]

t3[cols] = t3[cols].apply(pd.to_numeric, errors="coerce")

In [23]:
t3.head()

,year,spending_current,spending_constant,nominal_change_pct,real_growth_pct
0,2013–14,6608.756533,8509.998967,NaN,NaN
1,2014–15,6801.533849,8615.419165,2.916998,1.238780
2,2015–16,7057.752875,8773.923652,3.767077,1.839777
3,2016–17,7379.930619,8972.751459,4.564877,2.266122
4,2017–18,7494.462830,8953.393931,1.551942,-0.215737

In [24]:
t3["year"] = t3["year"].astype(str)

In [25]:
t3.shape

(17, 5)

In [26]:
t3.tail(10)

,year,spending_current,spending_constant,nominal_change_pct,real_growth_pct
7,2020–21,8725.989586,9821.941603,9.011442,6.863379
8,2021–22,9503.262635,10389.573549,8.907563,5.779223
9,2022–23,9693.700345,10171.191944,2.003919,-2.101930
10,2023–24,10036.919659,10036.919659,3.540643,-1.320123
12,2013–14 to 2018–19,NaN,NaN,3.422152,1.491807
13,2018–19 to 2023–24,NaN,NaN,5.119326,1.836439
14,2013–14 to 2023–24,NaN,NaN,4.267286,1.663977
17,(b) Constant price health spending is in 202...,NaN,NaN,NaN,NaN
18,"Note: For more information about concepts, def...",NaN,NaN,NaN,NaN
19,"Sources: AIHW Health Expenditure Database, Aus...",NaN,NaN,NaN,NaN

In [27]:
t3 = t3[t3["year"].str.match(r"\d{4}–\d{2}", na=False)]

In [28]:
t3 = t3.reset_index(drop=True)

In [29]:
t3.shape

(14, 5)

In [30]:
t3.tail(10)

,year,spending_current,spending_constant,nominal_change_pct,real_growth_pct
4,2017–18,7494.462830,8953.393931,1.551942,-0.215737
5,2018–19,7819.655341,9163.986294,4.339104,2.352095
6,2019–20,8004.654783,9191.120211,2.365826,0.296093
7,2020–21,8725.989586,9821.941603,9.011442,6.863379
8,2021–22,9503.262635,10389.573549,8.907563,5.779223
9,2022–23,9693.700345,10171.191944,2.003919,-2.101930
10,2023–24,10036.919659,10036.919659,3.540643,-1.320123
11,2013–14 to 2018–19,NaN,NaN,3.422152,1.491807
12,2018–19 to 2023–24,NaN,NaN,5.119326,1.836439
13,2013–14 to 2023–24,NaN,NaN,4.267286,1.663977

In [31]:
t3 = t3[t3["year"].str.match(r"^\d{4}–\d{2}$", na=False)]

In [32]:
t3 = t3.reset_index(drop=True)

In [33]:
t3.shape

(11, 5)

In [34]:
t3

,year,spending_current,spending_constant,nominal_change_pct,real_growth_pct
0,2013–14,6608.756533,8509.998967,NaN,NaN
1,2014–15,6801.533849,8615.419165,2.916998,1.238780
2,2015–16,7057.752875,8773.923652,3.767077,1.839777
3,2016–17,7379.930619,8972.751459,4.564877,2.266122
4,2017–18,7494.462830,8953.393931,1.551942,-0.215737
5,2018–19,7819.655341,9163.986294,4.339104,2.352095
6,2019–20,8004.654783,9191.120211,2.365826,0.296093
7,2020–21,8725.989586,9821.941603,9.011442,6.863379
8,2021–22,9503.262635,10389.573549,8.907563,5.779223
9,2022–23,9693.700345,10171.191944,2.003919,-2.101930
10,2023–24,10036.919659,10036.919659,3.540643,-1.320123

In [36]:
t3.to_csv("../data/processed/Expenditure/expenditure_avg_spending_per_person.csv", index=False)

In [37]:
t4.head(10)

,Year,NSW,Unnamed: 2,Vic,Unnamed: 4,Qld,Unnamed: 6,WA,Unnamed: 8,SA,Unnamed: 10,Tas,Unnamed: 12,ACT,Unnamed: 14,NT,Unnamed: 16,Australia
0,2013–14,62177.189085,NaN,47462.399618,NaN,42088.407834,NaN,21154.75603,NaN,14923.646534,NaN,4370.93584,NaN,3420.088549,NaN,2641.632347,NaN,198239.055836
1,2014–15,64133.401368,NaN,49159.291597,NaN,42707.682031,NaN,22035.953578,NaN,14952.284267,NaN,4465.722529,NaN,3547.299534,NaN,2644.870376,NaN,203646.505281
2,2015–16,65046.507008,NaN,50728.740271,NaN,44932.077886,NaN,22641.344846,NaN,15332.45252,NaN,5047.303678,NaN,3819.626271,NaN,2865.754167,NaN,210413.806646
3,2016–17,65866.657831,NaN,53014.329073,NaN,46456.196018,NaN,22517.609579,NaN,18843.062274,NaN,5056.011276,NaN,3866.121377,NaN,3139.775736,NaN,218759.763164
4,2017–18,67822.626965,NaN,55074.685474,NaN,47425.698224,NaN,22966.917801,NaN,16000.112726,NaN,5220.849223,NaN,3962.5818,NaN,3161.992746,NaN,221635.464958
5,2018–19,71604.996038,NaN,57098.227138,NaN,47930.049031,NaN,24554.473785,NaN,16355.074407,NaN,5606.372017,NaN,4249.708483,NaN,2996.699912,NaN,230395.60081
6,2019–20,72075.701684,NaN,58830.69819,NaN,49211.901738,NaN,24488.769606,NaN,16731.430129,NaN,5555.421271,NaN,4564.640236,NaN,3059.293911,NaN,234517.856766
7,2020–21,76367.784619,NaN,64112.927361,NaN,52500.980034,NaN,26932.403341,NaN,17705.73395,NaN,5953.522031,NaN,4983.247611,NaN,3139.248821,NaN,251695.847768
8,2021–22,79592.602321,NaN,70183.345742,NaN,55165.737181,NaN,28783.135747,NaN,18661.826727,NaN,6464.72734,NaN,5379.476911,NaN,3497.393498,NaN,267728.245467
9,2022–23,78992.143273,NaN,68992.002676,NaN,56006.904928,NaN,29325.118536,NaN,18830.876589,NaN,6384.093516,NaN,5754.92579,NaN,3372.319065,NaN,267658.384372

In [38]:
t4.tail(10)

,Year,NSW,Unnamed: 2,Vic,Unnamed: 4,Qld,Unnamed: 6,WA,Unnamed: 8,SA,Unnamed: 10,Tas,Unnamed: 12,ACT,Unnamed: 14,NT,Unnamed: 16,Australia
63,2013–14 to 2018–19,8.978331,NaN,3.846806,NaN,-8.441109,NaN,-10.726469,NaN,-0.112694,NaN,16.524773,NaN,3.647002,NaN,-1.694116,NaN,0.873188
64,2018–19 to 2023–24,1.729945,NaN,2.651794,NaN,10.016231,NaN,5.457528,NaN,12.843974,NaN,-6.38881,NaN,28.216197,NaN,9.718416,NaN,4.951355
65,2013–14 to 2023–24,5.291783,NaN,3.247571,NaN,0.364157,NaN,-2.971314,NaN,6.168171,NaN,4.44148,NaN,15.278898,NaN,3.855505,NaN,2.892068
66,(a) Constant price health spending is in 202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,1. The health spending increased in 2016–17...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,2. Components may not add to totals due to ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,"3. For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Source: AIHW Health Expenditure Database.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
t4 = t4.loc[:, ~t4.columns.str.contains("Unnamed")]

In [40]:
t4.head()

,Year,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Australia
0,2013–14,62177.189085,47462.399618,42088.407834,21154.75603,14923.646534,4370.93584,3420.088549,2641.632347,198239.055836
1,2014–15,64133.401368,49159.291597,42707.682031,22035.953578,14952.284267,4465.722529,3547.299534,2644.870376,203646.505281
2,2015–16,65046.507008,50728.740271,44932.077886,22641.344846,15332.45252,5047.303678,3819.626271,2865.754167,210413.806646
3,2016–17,65866.657831,53014.329073,46456.196018,22517.609579,18843.062274,5056.011276,3866.121377,3139.775736,218759.763164
4,2017–18,67822.626965,55074.685474,47425.698224,22966.917801,16000.112726,5220.849223,3962.5818,3161.992746,221635.464958

In [41]:
t4.columns = (
    t4.columns
    .str.replace("\xa0", " ")
    .str.strip()
    .str.lower()
)

In [42]:
t4.columns

Index(['year', 'nsw', 'vic', 'qld', 'wa', 'sa', 'tas', 'act', 'nt',
       'australia'],
      dtype='object')

In [43]:
t4 = t4[t4["year"].astype(str).str.match(r"^\d{4}–\d{2}$", na=False)]
t4 = t4.reset_index(drop=True)

In [44]:
t4.tail()

,year,nsw,vic,qld,wa,sa,tas,act,nt,australia
28,2019–20,5400.042431,3109.232337,2490.813856,1016.577632,774.912996,286.99324,238.355023,110.674893,13427.602409
29,2020–21,5305.095666,3088.955797,3002.632449,1069.300635,846.019463,290.695107,303.607979,157.876805,14064.183899
30,2021–22,4526.413985,3293.363251,2550.27189,1237.48979,829.15802,287.108528,337.689914,145.709476,13207.204854
31,2022–23,5143.786405,3583.537551,3408.816237,1389.551573,942.022142,299.977673,532.072091,160.324389,15460.08806
32,2023–24,5470.24121,3471.750687,3560.14327,1350.104235,1162.117375,347.34791,682.360082,164.648231,16208.713

In [45]:
cols = t4.columns.drop("year")
t4[cols] = t4[cols].apply(pd.to_numeric, errors="coerce")

In [46]:
t4_long = t4.melt(
    id_vars="year",
    var_name="state",
    value_name="spending"
)

In [47]:
t4_long.head()

      year state      spending
0  2013–14   nsw  62177.189085
1  2014–15   nsw  64133.401368
2  2015–16   nsw  65046.507008
3  2016–17   nsw  65866.657831
4  2017–18   nsw  67822.626965

In [48]:
t4_long.shape

(297, 3)

In [49]:
t4.columns

Index(['year', 'nsw', 'vic', 'qld', 'wa', 'sa', 'tas', 'act', 'nt',
       'australia'],
      dtype='object')

In [50]:
t4 = t4.drop(columns=["australia"])

In [51]:
t4_long = t4.melt(
    id_vars="year",
    var_name="state",
    value_name="spending"
)

In [52]:
t4_long.shape

(264, 3)

In [53]:
t4.shape

(33, 9)

In [54]:
t4.tail()

,year,nsw,vic,qld,wa,sa,tas,act,nt
28,2019–20,5400.042431,3109.232337,2490.813856,1016.577632,774.912996,286.993240,238.355023,110.674893
29,2020–21,5305.095666,3088.955797,3002.632449,1069.300635,846.019463,290.695107,303.607979,157.876805
30,2021–22,4526.413985,3293.363251,2550.271890,1237.489790,829.158020,287.108528,337.689914,145.709476
31,2022–23,5143.786405,3583.537551,3408.816237,1389.551573,942.022142,299.977673,532.072091,160.324389
32,2023–24,5470.241210,3471.750687,3560.143270,1350.104235,1162.117375,347.347910,682.360082,164.648231

In [55]:
t4

,year,nsw,vic,qld,wa,sa,tas,act,nt
0,2013–14,62177.189085,47462.399618,42088.407834,21154.756030,14923.646534,4370.935840,3420.088549,2641.632347
1,2014–15,64133.401368,49159.291597,42707.682031,22035.953578,14952.284267,4465.722529,3547.299534,2644.870376
2,2015–16,65046.507008,50728.740271,44932.077886,22641.344846,15332.452520,5047.303678,3819.626271,2865.754167
3,2016–17,65866.657831,53014.329073,46456.196018,22517.609579,18843.062274,5056.011276,3866.121377,3139.775736
4,2017–18,67822.626965,55074.685474,47425.698224,22966.917801,16000.112726,5220.849223,3962.581800,3161.992746
5,2018–19,71604.996038,57098.227138,47930.049031,24554.473785,16355.074407,5606.372017,4249.708483,2996.699912
6,2019–20,72075.701684,58830.698190,49211.901738,24488.769606,16731.430129,5555.421271,4564.640236,3059.293911
7,2020–21,76367.784619,64112.927361,52500.980034,26932.403341,17705.733950,5953.522031,4983.247611,3139.248821
8,2021–22,79592.602321,70183.345742,55165.737181,28783.135747,18661.826727,6464.727340,5379.476911,3497.393498
9,2022–23,78992.143273,68992.002676,56006.904928,29325.118536,18830.876589,6384.093516,5754.925790,3372.319065
10,2023–24,79977.915227,67960.484979,57357.362430,29527.587508,19376.167288,6625.400245,6118.691642,3542.362346
11,2013–14,58910.846978,44940.370507,38655.350559,19329.323428,14284.932264,4146.012495,3255.456100,2528.844616
12,2014–15,60287.584844,46396.152572,39611.012769,20434.662221,14314.096273,4220.618516,3383.265957,2494.871546
13,2015–16,61065.453628,47812.837963,41688.425111,20976.941858,14638.354296,4786.767948,3653.934971,2719.374758
14,2016–17,62389.935971,49569.360869,42960.060588,21830.941442,14530.995489,4782.037529,3633.558515,2886.224370
15,2017–18,64322.704007,51854.012685,44525.919409,22229.578843,15374.562929,4869.253807,3769.792881,3082.403406
16,2018–19,66584.317424,54052.325984,45721.110349,23519.380804,15719.950985,5123.173202,4052.784251,2893.147689
17,2019–20,66675.659253,55721.465853,46721.087882,23472.191974,15956.517132,5268.428032,4326.285214,2948.619019
18,2020–21,71062.688953,61023.971564,49498.347586,25863.102706,16859.714488,5662.826924,4679.639632,2981.372017
19,2021–22,75066.188337,66889.982491,52615.465291,27545.645957,17832.668707,6177.618812,5041.786997,3351.684022
20,2022–23,73848.356868,65408.465125,52598.088691,27935.566962,17888.854447,6084.115843,5222.853699,3211.994676
21,2023–24,74507.674017,64488.734292,53797.219160,28177.483273,18214.049913,6278.052334,5436.331560,3377.714115
22,2013–14,3266.342106,2522.029112,3433.057275,1825.432602,638.714270,224.923344,164.632449,112.787731
23,2014–15,3845.816524,2763.139026,3096.669262,1601.291357,638.187993,245.104013,164.033577,149.998830
24,2015–16,3981.053379,2915.902308,3243.652775,1664.402989,694.098224,260.535730,165.691300,146.379408
25,2016–17,3476.721860,3444.968203,3496.135430,686.668137,4312.066785,273.973747,232.562861,253.551366
26,2017–18,3499.922958,3220.672789,2899.778815,737.338958,625.549797,351.595416,192.788918,79.589340
27,2018–19,5020.678614,3045.901155,2208.938681,1035.092980,635.123422,483.198815,196.924232,103.552223
28,2019–20,5400.042431,3109.232337,2490.813856,1016.577632,774.912996,286.993240,238.355023,110.674893
29,2020–21,5305.095666,3088.955797,3002.632449,1069.300635,846.019463,290.695107,303.607979,157.876805
30,2021–22,4526.413985,3293.363251,2550.271890,1237.489790,829.158020,287.108528,337.689914,145.709476
31,2022–23,5143.786405,3583.537551,3408.816237,1389.551573,942.022142,299.977673,532.072091,160.324389
32,2023–24,5470.241210,3471.750687,3560.143270,1350.104235,1162.117375,347.347910,682.360082,164.648231

In [56]:
t4 = t4.iloc[:11]

In [57]:
t4 = t4.reset_index(drop=True)

In [58]:
t4.shape

(11, 9)

In [59]:
t4_long = t4.melt(
    id_vars="year",
    var_name="state",
    value_name="spending"
)

In [60]:
t4_long.shape

(88, 3)

In [61]:
t4_long

       year state      spending
0   2013–14   nsw  62177.189085
1   2014–15   nsw  64133.401368
2   2015–16   nsw  65046.507008
3   2016–17   nsw  65866.657831
4   2017–18   nsw  67822.626965
..      ...   ...           ...
83  2019–20    nt   3059.293911
84  2020–21    nt   3139.248821
85  2021–22    nt   3497.393498
86  2022–23    nt   3372.319065
87  2023–24    nt   3542.362346

[88 rows x 3 columns]

In [62]:
t4_long.to_csv(
    "../data/processed/Expenditure/expenditure_total_spending_by_state.csv",
    index=False
)

In [64]:
t5.head(10)

,Unnamed: 0,NSW,Unnamed: 2,Unnamed: 3,Vic,Unnamed: 5,Unnamed: 6,Qld,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,ACT,Unnamed: 20,Unnamed: 21,NT,Unnamed: 23,Unnamed: 24,Australia,Unnamed: 26
0,Year,($),Annual growth (%),NaN,($),Annual growth (%),NaN,($),Annual growth (%),NaN,...,Annual growth (%),NaN,($),Annual growth (%),NaN,($),Annual growth (%),NaN,($),Annual growth (%)
1,2013–14,8340.403245,. .,NaN,8137.455282,. .,NaN,8982.8099,. .,NaN,...,. .,NaN,8853.039592,..,NaN,10902.140892,. .,NaN,8509.998967,. .
2,2014–15,8480.818718,1.683557,NaN,8251.647936,1.403297,NaN,8996.274702,0.149895,NaN,...,1.964842,NaN,9049.672137,2.221074,NaN,10895.314893,-0.062612,NaN,8615.419165,1.23878
3,2015–16,8479.090978,-0.020372,NaN,8325.674104,0.897108,NaN,9351.239213,3.945683,NaN,...,12.660724,NaN,9576.022179,5.816233,NaN,11740.563589,7.75791,NaN,8773.923652,1.839777
4,2016–17,8449.182436,-0.352733,NaN,8501.63421,2.113464,NaN,9513.982464,1.740339,NaN,...,-1.034008,NaN,9455.439952,-1.25921,NaN,12759.944471,8.682555,NaN,8972.751459,2.266122
5,2017–18,8584.114733,1.596986,NaN,8661.979625,1.886054,NaN,9559.772791,0.481295,NaN,...,1.399241,NaN,9429.644524,-0.27281,NaN,12808.746367,0.382462,NaN,8953.393931,-0.215737
6,2018–19,8946.638777,4.223197,NaN,8811.869561,1.730435,NaN,9497.805585,-0.648208,NaN,...,5.136238,NaN,9865.651904,4.623794,NaN,12185.66978,-4.864462,NaN,9163.986294,2.352095
7,2019–20,8911.039169,-0.39791,NaN,8927.200581,1.308814,NaN,9593.447649,1.006991,NaN,...,-2.773543,NaN,10367.890931,5.090784,NaN,12425.395537,1.967276,NaN,9191.120211,0.296093
8,2020–21,9434.760834,5.877223,NaN,9762.604485,9.35796,NaN,10126.861168,5.560186,NaN,...,5.536986,NaN,11132.017448,7.370125,NaN,12667.506613,1.948518,NaN,9821.941603,6.863379
9,2021–22,9805.598547,3.930547,NaN,10706.820222,9.671761,NaN,10508.415989,3.76775,NaN,...,7.113387,NaN,11796.969137,5.973326,NaN,13961.650691,10.216249,NaN,10389.573549,5.779223

In [65]:
t5.tail(10)

,Unnamed: 0,NSW,Unnamed: 2,Unnamed: 3,Vic,Unnamed: 5,Unnamed: 6,Qld,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,ACT,Unnamed: 20,Unnamed: 21,NT,Unnamed: 23,Unnamed: 24,Australia,Unnamed: 26
20,Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1. The ACT per person figures need to be tre...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2. Australian average includes the ACT.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,3. Spending increased in 2016–17 for South ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,4. Tasmania has improved its health expendit...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Data for the period 2015–16 to 2017–18 i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,5. The Northern Territory reported the healt...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"6. For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Sources: AIHW Health Expenditure Database; Au...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
t5 = t5.loc[:, ~t5.columns.str.contains("Unnamed")]

In [67]:
t5.head()

,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Australia
0,($),($),($),($),($),($),($),($),($)
1,8340.403245,8137.455282,8982.8099,8454.503031,8893.435087,8520.093642,8853.039592,10902.140892,8509.998967
2,8480.818718,8251.647936,8996.274702,8714.619948,8831.269534,8687.500057,9049.672137,10895.314893,8615.419165
3,8479.090978,8325.674104,9351.239213,8886.817498,8987.701492,9787.400431,9576.022179,11740.563589,8773.923652
4,8449.182436,8501.63421,9513.982464,8763.059231,10957.944541,9686.19792,9455.439952,12759.944471,8972.751459

In [68]:
t5.insert(0, "year", expenditure_data["Table 5"]["Unnamed: 0"])

In [69]:
t5.head()

,year,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Australia
0,Year,($),($),($),($),($),($),($),($),($)
1,2013–14,8340.403245,8137.455282,8982.8099,8454.503031,8893.435087,8520.093642,8853.039592,10902.140892,8509.998967
2,2014–15,8480.818718,8251.647936,8996.274702,8714.619948,8831.269534,8687.500057,9049.672137,10895.314893,8615.419165
3,2015–16,8479.090978,8325.674104,9351.239213,8886.817498,8987.701492,9787.400431,9576.022179,11740.563589,8773.923652
4,2016–17,8449.182436,8501.63421,9513.982464,8763.059231,10957.944541,9686.19792,9455.439952,12759.944471,8972.751459

In [70]:
t5 = t5.drop(0).reset_index(drop=True)

In [71]:
t5.head()

,year,NSW,Vic,Qld,WA,SA,Tas,ACT,NT,Australia
0,2013–14,8340.403245,8137.455282,8982.8099,8454.503031,8893.435087,8520.093642,8853.039592,10902.140892,8509.998967
1,2014–15,8480.818718,8251.647936,8996.274702,8714.619948,8831.269534,8687.500057,9049.672137,10895.314893,8615.419165
2,2015–16,8479.090978,8325.674104,9351.239213,8886.817498,8987.701492,9787.400431,9576.022179,11740.563589,8773.923652
3,2016–17,8449.182436,8501.63421,9513.982464,8763.059231,10957.944541,9686.19792,9455.439952,12759.944471,8972.751459
4,2017–18,8584.114733,8661.979625,9559.772791,8833.674548,9218.492122,9821.731133,9429.644524,12808.746367,8953.393931

In [72]:
t5 = t5.drop(columns=["Australia"])

In [73]:
t5.head()

,year,NSW,Vic,Qld,WA,SA,Tas,ACT,NT
0,2013–14,8340.403245,8137.455282,8982.8099,8454.503031,8893.435087,8520.093642,8853.039592,10902.140892
1,2014–15,8480.818718,8251.647936,8996.274702,8714.619948,8831.269534,8687.500057,9049.672137,10895.314893
2,2015–16,8479.090978,8325.674104,9351.239213,8886.817498,8987.701492,9787.400431,9576.022179,11740.563589
3,2016–17,8449.182436,8501.63421,9513.982464,8763.059231,10957.944541,9686.19792,9455.439952,12759.944471
4,2017–18,8584.114733,8661.979625,9559.772791,8833.674548,9218.492122,9821.731133,9429.644524,12808.746367

In [74]:
cols = t5.columns.drop("year")
t5[cols] = t5[cols].apply(pd.to_numeric, errors="coerce")

In [75]:
t5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    29 non-null     object
 1   NSW     11 non-null     float64
 2   Vic     11 non-null     float64
 3   Qld     11 non-null     float64
 4   WA      11 non-null     float64
 5   SA      11 non-null     float64
 6   Tas     11 non-null     float64
 7   ACT     11 non-null     float64
 8   NT      11 non-null     float64
dtypes: float64(8), object(1)
memory usage: 2.2+ KB

In [76]:
t5 = t5[t5["year"].astype(str).str.match(r"^\d{4}–\d{2}$", na=False)]
t5 = t5.reset_index(drop=True)

In [77]:
t5.shape

(11, 9)

In [78]:
t5.head()

,year,NSW,Vic,Qld,WA,SA,Tas,ACT,NT
0,2013–14,8340.403245,8137.455282,8982.809900,8454.503031,8893.435087,8520.093642,8853.039592,10902.140892
1,2014–15,8480.818718,8251.647936,8996.274702,8714.619948,8831.269534,8687.500057,9049.672137,10895.314893
2,2015–16,8479.090978,8325.674104,9351.239213,8886.817498,8987.701492,9787.400431,9576.022179,11740.563589
3,2016–17,8449.182436,8501.634210,9513.982464,8763.059231,10957.944541,9686.197920,9455.439952,12759.944471
4,2017–18,8584.114733,8661.979625,9559.772791,8833.674548,9218.492122,9821.731133,9429.644524,12808.746367

In [79]:
t5_long = t5.melt(
    id_vars="year",
    var_name="state",
    value_name="avg_spending_per_person"
)

In [80]:
t5_long.shape

(88, 3)

In [81]:
t5_long.to_csv(
    "../data/processed/Expenditure/expenditure_avg_spending_by_state.csv",
    index=False
)

In [82]:
t28.head()

,Year,Hospitals,Primary health care,Referred medical services,Other services,Research,Capital,Total
0,2013–14,58762.848998,53693.720694,16850.285444,10531.879226,4997.11406,9114.071,153949.919423
1,2014–15,62215.944781,55313.012035,17636.972139,11307.793133,4730.505991,9566.661,160770.88908
2,2015–16,68489.87919,58219.130838,15522.914291,11928.484181,4891.828721,10204.83722,169257.074441
3,2016–17,71948.057256,60842.303578,16157.45991,13046.657957,5264.192669,12667.395,179926.06637
4,2017–18,77062.291956,63026.448617,17022.518204,13803.071636,5328.207096,9278.033427,185520.570935

In [83]:
t28.tail(10)

,Year,Hospitals,Primary health care,Referred medical services,Other services,Research,Capital,Total
31,2021–22,40.219673,36.249548,8.941722,6.835081,2.966305,4.78767,100
32,2022–23,41.978513,33.667663,8.357512,7.295258,2.889171,5.811884,100
33,2023–24,42.08578,32.95387,8.735121,7.407461,2.825327,5.992441,100
34,Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,1. Spending on the medical expenses tax reb...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2. Other services include patient transport...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,3. Components may not add to totals due to ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"4. For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Source: AIHW Health Expenditure Database.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
t28.columns

Index(['Year', 'Hospitals', 'Primary health care', 'Referred medical services',
       'Other services', 'Research', 'Capital', 'Total'],
      dtype='object')

In [86]:
t28.columns = t28.columns.str.strip()

In [88]:
t28 = t28[t28["Year"].astype(str).str.match(r"^\d{4}–\d{2}$", na=False)]
t28 = t28.reset_index(drop=True)

In [91]:
t28.head()

,Year,Hospitals,Primary health care,Referred medical services,Other services,Research,Capital,Total
0,2013–14,58762.848998,53693.720694,16850.285444,10531.879226,4997.11406,9114.071,153949.919423
1,2014–15,62215.944781,55313.012035,17636.972139,11307.793133,4730.505991,9566.661,160770.88908
2,2015–16,68489.87919,58219.130838,15522.914291,11928.484181,4891.828721,10204.83722,169257.074441
3,2016–17,71948.057256,60842.303578,16157.45991,13046.657957,5264.192669,12667.395,179926.06637
4,2017–18,77062.291956,63026.448617,17022.518204,13803.071636,5328.207096,9278.033427,185520.570935

In [90]:
t28.shape

(22, 8)

In [92]:
t28

,Year,Hospitals,Primary health care,Referred medical services,Other services,Research,Capital,Total
0,2013–14,58762.848998,53693.720694,16850.285444,10531.879226,4997.11406,9114.071,153949.919423
1,2014–15,62215.944781,55313.012035,17636.972139,11307.793133,4730.505991,9566.661,160770.88908
2,2015–16,68489.87919,58219.130838,15522.914291,11928.484181,4891.828721,10204.83722,169257.074441
3,2016–17,71948.057256,60842.303578,16157.45991,13046.657957,5264.192669,12667.395,179926.06637
4,2017–18,77062.291956,63026.448617,17022.518204,13803.071636,5328.207096,9278.033427,185520.570935
5,2018–19,82125.069734,66049.285538,17649.326591,14433.014989,5893.42487,10447.094,196597.215722
6,2019–20,86625.226494,67452.65121,18081.071109,14277.301799,6663.072427,11145.039,204244.362039
7,2020–21,92339.596646,76547.589456,20729.153664,15404.055702,6857.599911,11733.123,223611.11838
8,2021–22,98493.538024,88771.140116,21897.290964,16738.358957,7264.153077,11724.476,244888.957137
9,2022–23,107084.260287,85883.861102,21319.429653,18609.694212,7370.072875,14825.712,255093.030129
10,2023–24,113836.131357,89135.595135,23627.276705,20036.141664,7642.113803,16208.713,270485.971664
11,2013–14,38.170107,34.877394,10.945303,6.841107,3.245935,5.920153,100
12,2014–15,38.698514,34.404868,10.970252,7.033483,2.94239,5.950493,100
13,2015–16,40.465002,34.396867,9.171206,7.047554,2.890177,6.029194,100
14,2016–17,39.987568,33.815169,8.980055,7.251122,2.925753,7.040333,100
15,2017–18,41.538408,33.972755,9.175542,7.440184,2.87203,5.001081,100
16,2018–19,41.773262,33.596247,8.977404,7.341414,2.997715,5.313958,100
17,2019–20,42.412542,33.025465,8.852666,6.990304,3.262304,5.456718,100
18,2020–21,41.294725,34.232461,9.27018,6.88877,3.066753,5.247111,100
19,2021–22,40.219673,36.249548,8.941722,6.835081,2.966305,4.78767,100
20,2022–23,41.978513,33.667663,8.357512,7.295258,2.889171,5.811884,100
21,2023–24,42.08578,32.95387,8.735121,7.407461,2.825327,5.992441,100

In [93]:
t28 = t28.iloc[:11]

In [94]:
t28 = t28.reset_index(drop=True)

In [95]:
t28.shape

(11, 8)

In [96]:
t28 = t28.drop(columns=["Total"])

In [97]:
t28.head()

,Year,Hospitals,Primary health care,Referred medical services,Other services,Research,Capital
0,2013–14,58762.848998,53693.720694,16850.285444,10531.879226,4997.11406,9114.071
1,2014–15,62215.944781,55313.012035,17636.972139,11307.793133,4730.505991,9566.661
2,2015–16,68489.87919,58219.130838,15522.914291,11928.484181,4891.828721,10204.83722
3,2016–17,71948.057256,60842.303578,16157.45991,13046.657957,5264.192669,12667.395
4,2017–18,77062.291956,63026.448617,17022.518204,13803.071636,5328.207096,9278.033427

In [98]:
t28_long = t28.melt(
    id_vars="Year",
    var_name="expenditure_area",
    value_name="spending"
)

In [100]:
t28_long.head()

      Year expenditure_area      spending
0  2013–14        Hospitals  58762.848998
1  2014–15        Hospitals  62215.944781
2  2015–16        Hospitals   68489.87919
3  2016–17        Hospitals  71948.057256
4  2017–18        Hospitals  77062.291956

In [101]:
t28_long.shape

(66, 3)

In [102]:
t28_long.to_csv(
    "../data/processed/Expenditure/expenditure_spending_by_area.csv",
    index=False
)

In [103]:
t29.head()

,Year,Australian Government,Unnamed: 2,Unnamed: 3,State and territory government,Unnamed: 5,Unnamed: 6,Non-government,Unnamed: 8,Unnamed: 9,Total,Unnamed: 11
0,NaN,($ million),Annual growth (%),NaN,($ million),Annual growth (%),NaN,($ million),Annual growth (%),NaN,($ million),Annual growth (%)
1,2013–14,27383.301507,. .,NaN,33055.876117,. .,NaN,16189.544104,. .,NaN,76628.721728,. .
2,2014–15,28953.532467,5.734265,NaN,32725.589616,-0.999176,NaN,17543.69267,8.36434,NaN,79222.814753,3.385275
3,2015–16,34225.169753,18.207234,NaN,34491.112839,5.394932,NaN,16901.537283,-3.660321,NaN,85617.819875,8.072176
4,2016–17,36014.536648,5.228219,NaN,34651.88972,0.46614,NaN,17660.105228,4.488159,NaN,88326.531595,3.163724

In [105]:
t29.tail(10)

,Year,Australian Government,Unnamed: 2,Unnamed: 3,State and territory government,Unnamed: 5,Unnamed: 6,Non-government,Unnamed: 8,Unnamed: 9,Total,Unnamed: 11
11,2023–24,41168.783417,-0.665521,NaN,53146.485747,2.166948,NaN,19520.862193,2.443285,NaN,113836.131357,1.170452
12,Average annual growth rate (%),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2013–14 to 2018–19,. .,6.168109,NaN,. .,3.35621,NaN,. .,3.846348,NaN,. .,4.496333
14,2018–19 to 2023–24,. .,2.193285,NaN,. .,6.391908,NaN,. .,-0.031852,NaN,. .,3.580179
15,2013–14 to 2023–24,. .,4.161739,NaN,. .,4.863075,NaN,. .,1.888798,NaN,. .,4.037248
16,. . not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,(a) Constant price health spending is in 202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,"Note: For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Source: AIHW Health Expenditure Database.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
t29 = t29.loc[:, ~t29.columns.str.contains("Unnamed")]

In [107]:
t29.head()

,Year,Australian Government,State and territory government,Non-government,Total
0,NaN,($ million),($ million),($ million),($ million)
1,2013–14,27383.301507,33055.876117,16189.544104,76628.721728
2,2014–15,28953.532467,32725.589616,17543.69267,79222.814753
3,2015–16,34225.169753,34491.112839,16901.537283,85617.819875
4,2016–17,36014.536648,34651.88972,17660.105228,88326.531595

In [108]:
t29 = t29.drop(0).reset_index(drop=True)

In [109]:
t29.head()

,Year,Australian Government,State and territory government,Non-government,Total
0,2013–14,27383.301507,33055.876117,16189.544104,76628.721728
1,2014–15,28953.532467,32725.589616,17543.69267,79222.814753
2,2015–16,34225.169753,34491.112839,16901.537283,85617.819875
3,2016–17,36014.536648,34651.88972,17660.105228,88326.531595
4,2017–18,36163.440528,37220.882203,18892.261719,92276.58445

In [111]:
t29.columns = t29.columns.str.strip()

In [112]:
t29.columns

Index(['Year', 'Australian Government', 'State and territory government',
       'Non-government', 'Total'],
      dtype='object')

In [113]:
t29 = t29[t29["Year"].astype(str).str.match(r"^\d{4}–\d{2}$", na=False)]
t29 = t29.reset_index(drop=True)

In [114]:
t29.shape

(11, 5)

In [115]:
t29 = t29.drop(columns=["Total"])

In [116]:
t29.head()

      Year Australian Government State and territory government Non-government
0  2013–14          27383.301507                   33055.876117   16189.544104
1  2014–15          28953.532467                   32725.589616    17543.69267
2  2015–16          34225.169753                   34491.112839   16901.537283
3  2016–17          36014.536648                    34651.88972   17660.105228
4  2017–18          36163.440528                   37220.882203   18892.261719

In [117]:
t29_long = t29.melt(
    id_vars="Year",
    var_name="funding_source",
    value_name="spending"
)

In [118]:
t29_long.shape

(33, 3)

In [119]:
t29_long.head()

      Year         funding_source      spending
0  2013–14  Australian Government  27383.301507
1  2014–15  Australian Government  28953.532467
2  2015–16  Australian Government  34225.169753
3  2016–17  Australian Government  36014.536648
4  2017–18  Australian Government  36163.440528

In [120]:
t29_long.to_csv(
    "../data/processed/Expenditure/expenditure_hospital_funding_source.csv",
    index=False
)

In [121]:
t30.head()

,Unnamed: 0,Australian Government,Unnamed: 2,Unnamed: 3,State and territory government,Unnamed: 5,Unnamed: 6,Non-government,Unnamed: 8,Unnamed: 9,Total,Unnamed: 11
0,Year,($ million),Annual growth (%),NaN,($ million),Annual growth (%),NaN,($ million),Annual growth (%),NaN,($ million),Annual growth (%)
1,2013–14,22123.237889,. .,NaN,32995.334665,. .,NaN,5081.920112,. .,NaN,60200.492667,. .
2,2014–15,23725.354479,7.241782,NaN,32553.945379,-1.337732,NaN,5430.668986,6.862541,NaN,61709.968844,2.507415
3,2015–16,26324.554177,10.955367,NaN,34280.072542,5.302359,NaN,4219.980927,-22.293534,NaN,64824.607646,5.047221
4,2016–17,27988.009714,6.319026,NaN,34430.71379,0.439443,NaN,4502.806494,6.702058,NaN,66921.529998,3.234763

In [122]:
t30.tail(10)

,Unnamed: 0,Australian Government,Unnamed: 2,Unnamed: 3,State and territory government,Unnamed: 5,Unnamed: 6,Non-government,Unnamed: 8,Unnamed: 9,Total,Unnamed: 11
13,2013–14 to 2018–19,. .,5.61663,NaN,. .,3.31258,NaN,. .,0.513953,NaN,. .,3.965814
14,2018–19 to 2023–24,. .,2.652479,NaN,. .,6.282296,NaN,. .,-0.857045,NaN,. .,4.425452
15,2013–14 to 2023–24,. .,4.124007,NaN,. .,4.786918,NaN,. .,-0.173899,NaN,. .,4.195379
16,. . not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,(a) Constant price health spending is in 202...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1. Public hospital services exclude certai...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"2. For more information about concepts, def...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Source: AIHW Health Expenditure Database.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
t30 = t30.loc[:, ~t30.columns.str.contains("Unnamed")]

In [124]:
t30.head()

,Australian Government,State and territory government,Non-government,Total
0,($ million),($ million),($ million),($ million)
1,22123.237889,32995.334665,5081.920112,60200.492667
2,23725.354479,32553.945379,5430.668986,61709.968844
3,26324.554177,34280.072542,4219.980927,64824.607646
4,27988.009714,34430.71379,4502.806494,66921.529998

In [125]:
t30.insert(0, "Year", expenditure_data["Table 30"]["Unnamed: 0"])

In [126]:
t30.head()

,Year,Australian Government,State and territory government,Non-government,Total
0,Year,($ million),($ million),($ million),($ million)
1,2013–14,22123.237889,32995.334665,5081.920112,60200.492667
2,2014–15,23725.354479,32553.945379,5430.668986,61709.968844
3,2015–16,26324.554177,34280.072542,4219.980927,64824.607646
4,2016–17,27988.009714,34430.71379,4502.806494,66921.529998

In [127]:
t30 = t30.drop(0).reset_index(drop=True)

In [128]:
t30.head()

,Year,Australian Government,State and territory government,Non-government,Total
0,2013–14,22123.237889,32995.334665,5081.920112,60200.492667
1,2014–15,23725.354479,32553.945379,5430.668986,61709.968844
2,2015–16,26324.554177,34280.072542,4219.980927,64824.607646
3,2016–17,27988.009714,34430.71379,4502.806494,66921.529998
4,2017–18,28207.569871,37004.984787,5086.432286,70298.986945

In [129]:
t30 = t30[t30["Year"].astype(str).str.match(r"^\d{4}–\d{2}$", na=False)]
t30 = t30.reset_index(drop=True)

In [130]:
t30.shape

(11, 5)

In [131]:
t30

,Year,Australian Government,State and territory government,Non-government,Total
0,2013–14,22123.237889,32995.334665,5081.920112,60200.492667
1,2014–15,23725.354479,32553.945379,5430.668986,61709.968844
2,2015–16,26324.554177,34280.072542,4219.980927,64824.607646
3,2016–17,27988.009714,34430.71379,4502.806494,66921.529998
4,2017–18,28207.569871,37004.984787,5086.432286,70298.986945
5,2018–19,29074.363071,38834.577007,5213.862853,73122.802931
6,2019–20,30938.84214,40897.10523,4696.603035,76532.550406
7,2020–21,32400.796201,42435.527463,5053.236986,79889.56065
8,2021–22,33411.282762,47532.417166,4362.43023,85306.130158
9,2022–23,33418.131139,51750.843735,4774.428991,89943.403865
10,2023–24,33140.375015,52665.138009,4994.234209,90799.747234

In [132]:
t30 = t30.drop(columns=["Total"])

In [133]:
t30.head()

      Year Australian Government State and territory government Non-government
0  2013–14          22123.237889                   32995.334665    5081.920112
1  2014–15          23725.354479                   32553.945379    5430.668986
2  2015–16          26324.554177                   34280.072542    4219.980927
3  2016–17          27988.009714                    34430.71379    4502.806494
4  2017–18          28207.569871                   37004.984787    5086.432286

In [134]:
t30_long = t30.melt(
    id_vars="Year",
    var_name="funding_source",
    value_name="spending"
)

In [135]:
t30_long.shape

(33, 3)

In [136]:
t30_long.to_csv(
    "../data/processed/Expenditure/expenditure_public_hospital_funding_source.csv",
    index=False
)

In [138]:
tA3 = expenditure_data["Table A3"]

tA3.head(10)

,Unnamed: 0,Government,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Non-government,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,Australian Government,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Area of expenditure,DVA,Health and other,Premium rebates,Total,State and local,Total,NaN,HIF,Individuals,Other,Total,NaN,Total health expenditure
2,Hospitals,1153,36221,3794,41169,53146,94315,NaN,11497,3876,4147,19521,NaN,113836
3,Public hospital services,445,32368,328,33140,52665,85806,NaN,994,1464,2536,4994,NaN,90800
4,Private hospitals,708,3854,3466,8028,481,8510,NaN,10503,2412,1612,14527,NaN,23036
5,Primary health care,860,35851,1227,37937,13637,51574,NaN,3717,30680,3164,37561,NaN,89136
6,Unreferred medical services,134,11316,. .,11450,. .,11450,NaN,. .,1672,1490,3162,NaN,14612
7,Dental services,96,500,860,1456,1058,2514,NaN,2606,7986,59,10651,NaN,13166
8,Other health practitioners,279,2505,340,3124,16,3140,NaN,1030,3542,926,5498,NaN,8638
9,Community health and other,11,2118,1,2129,10747,12876,NaN,2,90,461,553,NaN,13429

In [139]:
tA3.tail(10)

,Unnamed: 0,Government,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Non-government,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
21,Medical expenses tax rebate,. .,—,. .,—,. .,—,NaN,. .,—,. .,—,NaN,—
22,Total health expenditure,3188,96083,6924,106195,81968,188163,NaN,20981,44050,17292,82323,NaN,270486
23,. . not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,— rounded to zero,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,‘Health and other’ figures include Australian ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,‘HIF’ figures include health spending by Healt...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,‘Other’ figures include health spending funded...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Notes to detailed expenditure tables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
tA3 = tA3.drop(0).reset_index(drop=True)

In [141]:
tA3.head()

,Unnamed: 0,Government,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Non-government,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Area of expenditure,DVA,Health and other,Premium rebates,Total,State and local,Total,NaN,HIF,Individuals,Other,Total,NaN,Total health expenditure
1,Hospitals,1153,36221,3794,41169,53146,94315,NaN,11497,3876,4147,19521,NaN,113836
2,Public hospital services,445,32368,328,33140,52665,85806,NaN,994,1464,2536,4994,NaN,90800
3,Private hospitals,708,3854,3466,8028,481,8510,NaN,10503,2412,1612,14527,NaN,23036
4,Primary health care,860,35851,1227,37937,13637,51574,NaN,3717,30680,3164,37561,NaN,89136

In [142]:
tA3.columns = tA3.iloc[0]
tA3 = tA3.drop(0).reset_index(drop=True)

In [143]:
tA3.head()

,Area of expenditure,DVA,Health and other,Premium rebates,Total,State and local,Total,NaN,HIF,Individuals,Other,Total,NaN,Total health expenditure
0,Hospitals,1153,36221,3794,41169,53146,94315,NaN,11497,3876,4147,19521,NaN,113836
1,Public hospital services,445,32368,328,33140,52665,85806,NaN,994,1464,2536,4994,NaN,90800
2,Private hospitals,708,3854,3466,8028,481,8510,NaN,10503,2412,1612,14527,NaN,23036
3,Primary health care,860,35851,1227,37937,13637,51574,NaN,3717,30680,3164,37561,NaN,89136
4,Unreferred medical services,134,11316,. .,11450,. .,11450,NaN,. .,1672,1490,3162,NaN,14612

In [144]:
tA3 = tA3.loc[:, ~tA3.columns.isna()]

In [145]:
tA3.head()

,Area of expenditure,DVA,Health and other,Premium rebates,Total,State and local,Total,HIF,Individuals,Other,Total,Total health expenditure
0,Hospitals,1153,36221,3794,41169,53146,94315,11497,3876,4147,19521,113836
1,Public hospital services,445,32368,328,33140,52665,85806,994,1464,2536,4994,90800
2,Private hospitals,708,3854,3466,8028,481,8510,10503,2412,1612,14527,23036
3,Primary health care,860,35851,1227,37937,13637,51574,3717,30680,3164,37561,89136
4,Unreferred medical services,134,11316,. .,11450,. .,11450,. .,1672,1490,3162,14612

In [147]:
list(tA3.columns)

['Area\xa0of\xa0expenditure',
 'DVA',
 'Health\xa0and other',
 'Premium rebates',
 'Total',
 'State\xa0and local',
 'Total',
 'HIF',
 'Individuals',
 'Other',
 'Total',
 'Total\xa0health expenditure']

In [148]:
tA3.columns = tA3.columns.str.replace("\xa0", " ").str.strip()

In [149]:
list(tA3.columns)

['Area of expenditure',
 'DVA',
 'Health and other',
 'Premium rebates',
 'Total',
 'State and local',
 'Total',
 'HIF',
 'Individuals',
 'Other',
 'Total',
 'Total health expenditure']

In [150]:
tA3 = tA3.drop(columns=["Total health expenditure"])

In [151]:
tA3.head()

,Area of expenditure,DVA,Health and other,Premium rebates,Total,State and local,Total,HIF,Individuals,Other,Total
0,Hospitals,1153,36221,3794,41169,53146,94315,11497,3876,4147,19521
1,Public hospital services,445,32368,328,33140,52665,85806,994,1464,2536,4994
2,Private hospitals,708,3854,3466,8028,481,8510,10503,2412,1612,14527
3,Primary health care,860,35851,1227,37937,13637,51574,3717,30680,3164,37561
4,Unreferred medical services,134,11316,. .,11450,. .,11450,. .,1672,1490,3162

In [152]:
tA3 = tA3.loc[:, tA3.columns != "Total"]

In [153]:
tA3.head()

,Area of expenditure,DVA,Health and other,Premium rebates,State and local,HIF,Individuals,Other
0,Hospitals,1153,36221,3794,53146,11497,3876,4147
1,Public hospital services,445,32368,328,52665,994,1464,2536
2,Private hospitals,708,3854,3466,481,10503,2412,1612
3,Primary health care,860,35851,1227,13637,3717,30680,3164
4,Unreferred medical services,134,11316,. .,. .,. .,1672,1490

In [154]:
tA3

,Area of expenditure,DVA,Health and other,Premium rebates,State and local,HIF,Individuals,Other
0,Hospitals,1153,36221,3794,53146,11497,3876,4147
1,Public hospital services,445,32368,328,52665,994,1464,2536
2,Private hospitals,708,3854,3466,481,10503,2412,1612
3,Primary health care,860,35851,1227,13637,3717,30680,3164
4,Unreferred medical services,134,11316,. .,. .,. .,1672,1490
5,Dental services,96,500,860,1058,2606,7986,59
6,Other health practitioners,279,2505,340,16,1030,3542,926
7,Community health and other,11,2118,1,10747,2,90,461
8,Public health,. .,3370,. .,1816,. .,28,110
9,Benefit-paid pharmaceuticals,340,14221,. .,. .,. .,1601,. .
10,All other medications,. .,1822,26,. .,78,15762,119
11,Referred medical services,713,14807,657,. .,1991,5459,. .
12,Other services,456,3171,1246,7004,3776,4032,350
13,Patient transport services,126,115,121,5080,368,558,161
14,Aids and appliances,157,816,283,. .,858,3458,185
15,Administration,173,2239,842,1924,2551,15,4
16,Research,5,5896,. .,1176,. .,2,563
17,Total recurrent expenditure,3188,95946,6924,74964,20981,44050,8225
18,Capital expenditure,. .,137,. .,7004,. .,. .,9068
19,Medical expenses tax rebate,. .,—,. .,. .,. .,—,. .
20,Total health expenditure,3188,96083,6924,81968,20981,44050,17292
21,. . not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,— rounded to zero,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,‘Health and other’ figures include Australian ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,‘HIF’ figures include health spending by Healt...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,‘Other’ figures include health spending funded...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Notes to detailed expenditure tables,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Link to Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [155]:
tA3 = tA3[~tA3["Area of expenditure"].astype(str).str.contains("Notes|Link|not applicable|rounded", na=False)]

In [156]:
tA3 = tA3.reset_index(drop=True)

In [157]:
tA3.tail()

,Area of expenditure,DVA,Health and other,Premium rebates,State and local,HIF,Individuals,Other
19,Medical expenses tax rebate,. .,—,. .,. .,. .,—,. .
20,Total health expenditure,3188,96083,6924,81968,20981,44050,17292
21,‘Health and other’ figures include Australian ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,‘HIF’ figures include health spending by Healt...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,‘Other’ figures include health spending funded...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [158]:
tA3 = tA3[~tA3["Area of expenditure"].astype(str).str.contains("figures include", na=False)]
tA3 = tA3.reset_index(drop=True)

In [159]:
tA3.tail()

,Area of expenditure,DVA,Health and other,Premium rebates,State and local,HIF,Individuals,Other
16,Research,5,5896,. .,1176,. .,2,563
17,Total recurrent expenditure,3188,95946,6924,74964,20981,44050,8225
18,Capital expenditure,. .,137,. .,7004,. .,. .,9068
19,Medical expenses tax rebate,. .,—,. .,. .,. .,—,. .
20,Total health expenditure,3188,96083,6924,81968,20981,44050,17292

In [160]:
tA3_long = tA3.melt(
    id_vars="Area of expenditure",
    var_name="funding_source",
    value_name="spending"
)

In [161]:
tA3_long.shape

(147, 3)

In [162]:
tA3_long

                Area of expenditure funding_source spending
0                         Hospitals            DVA     1153
1          Public hospital services            DVA      445
2                 Private hospitals            DVA      708
3               Primary health care            DVA      860
4       Unreferred medical services            DVA      134
..                              ...            ...      ...
142                        Research          Other      563
143     Total recurrent expenditure          Other     8225
144             Capital expenditure          Other     9068
145     Medical expenses tax rebate          Other      . .
146        Total health expenditure          Other    17292

[147 rows x 3 columns]

In [163]:
tA3_long.to_csv(
    "../data/processed/Expenditure/expenditure_area_funding_matrix.csv",
    index=False
)